{
 "title": "Health-check",
 "tags": [
  "pgwatch3",
  "postgres"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbname", "query": { "query": "label_values(dbname)" } }
  ]
 },
 "panels": [
  {
   "title": "Instance state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_over_time(pgwatch3_db_stats_in_recovery_int{dbname='$dbname'}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(pgwatch3_db_stats_postmaster_uptime_s{dbname='$dbname'}))"
    }
   ]
  },
  {
   "title": "Server version num.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgwatch3_settings_server_version_num{dbname='$dbname'})"
    }
   ]
  },
  {
   "title": "Longest query duration",
   "type": "stat",
   "description": "Over the selected time range",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_backends_longest_query_seconds{dbname='$dbname'}[$__interval]))"
    }
   ]
  },
  {
   "title": "Active connections (max.)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_backends_active{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Max. connections",
   "type": "stat",
   "description": "PostgreSQL configurations setting. Changing requires restart. Numbers above 500+ are not recommended",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgwatch3_settings_max_connections{dbname='$dbname'})"
    }
   ]
  },
  {
   "title": "Blocked sessions (max.)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_backends_waiting{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Shared Buffers hit pct. (avg.)",
   "type": "stat",
   "description": "Shared Buffers is the Postgres -managed file cache and 90%+ is what you normally want to see for best performance.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(increase(pgwatch3_db_stats_blks_hit{dbname='$dbname'}[$__range])) / (avg(increase(pgwatch3_db_stats_blks_read{dbname='$dbname'}[$__range])) + avg(increase(pgwatch3_db_stats_blks_hit{dbname='$dbname'}[$__range])))"
    }
   ]
  },
  {
   "title": "TX rollback pct. (avg.)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(increase(pgwatch3_db_stats_xact_rollback{dbname='$dbname'}[$__range])) / (avg(increase(pgwatch3_db_stats_xact_rollback{dbname='$dbname'}[$__range])) + avg(increase(pgwatch3_db_stats_xact_commit{dbname='$dbname'}[$__range])))"
    }
   ]
  },
  {
   "title": "TPS (avg.)",
   "type": "stat",
   "description": "Transactions per Second.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(pgwatch3_db_stats_xact_rollback{dbname='$dbname'}[$__range])) + avg(rate(pgwatch3_db_stats_xact_commit{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "QPS (avg.)",
   "type": "stat",
   "description": "Transactions per Second.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(pgwatch3_stat_statements_calls_calls{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "\"Idle in TX\" (max.)",
   "type": "stat",
   "description": "Open transactions where no queries are being executed. Bad for the database health generally.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_backends_idleintransaction{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "INSERT-s per minute (avg.)",
   "type": "stat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * avg(rate(pgwatch3_db_stats_tup_inserted{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "UPDATE-s per minute (avg.)",
   "type": "stat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * avg(rate(pgwatch3_db_stats_tup_updated{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "DELETE-s per minute (avg.)",
   "type": "stat",
   "description": "On non-temporary  tables",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * avg(rate(pgwatch3_db_stats_tup_deleted{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Tuples fetched vs returned",
   "type": "stat",
   "description": "Percentage of rows touched by queries that are actually returned to the client. Low numbers (< 10%) for an OLTP workload can hint at missing indexes",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(increase(pgwatch3_db_stats_tup_fetched{dbname='$dbname'}[$__range])) / avg(increase(pgwatch3_db_stats_tup_returned{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgwatch3_db_size_size_b{dbname='$dbname'})"
    }
   ]
  },
  {
   "title": "DB size change (1d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(delta(pgwatch3_db_size_size_b{dbname='$dbname'}[1d]))"
    }
   ]
  },
  {
   "title": "Checkpoints requested",
   "type": "stat",
   "description": "Checkpoints should normally be performed by the background \"Checkpointer\" process. If seeing high numbers then adjusting server configuration is recommended.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(pgwatch3_bgwriter_checkpoints_req{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "WAL per second (avg.)",
   "type": "stat",
   "description": "Transaction logs generation velocity.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(pgwatch3_wal_xlog_location_b{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Temp. bytes written (tot.)",
   "type": "stat",
   "description": "For selected timeframe. Postgres writes temporary files to disk when sorting / grouping  big amounts of data that doesn't fit into \"work_mem\" / \"\"maintenance_work_mem\"",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(pgwatch3_db_stats_temp_bytes{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Seq. scans on >100 MB tables (tot.)",
   "type": "stat",
   "description": "For selected timeframe. Frequent sequential scans on bigger tables should usually be avoided.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(increase(pgwatch3_table_stats_seq_scan{dbname='$dbname',table_size_cardinality_mb=~\"3|4|5|6|7|8\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Longest AUTOVACUUM duration (1d)",
   "type": "stat",
   "description": "Long running AUTOVACUUM processes can hint at workload or configuration  problems",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_backends_longest_autovacuum_seconds{dbname='$dbname'}[1d]))"
    }
   ]
  },
  {
   "title": "Backup duration (1d)",
   "type": "stat",
   "description": "Based on db_stats.backup_duration_s  / pg_backup_start_time() [9.3+] function. N/A if no backup in progress.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_db_stats_backup_duration_s{dbname='$dbname'}[1d]))"
    }
   ]
  },
  {
   "title": "Max. table FREEZE age",
   "type": "stat",
   "description": "Max. age since last VACUUM FREEZE. Could hint at problems when going into 100s of millions",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_table_stats_tx_freeze_age{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Max. session XMIN horizon age",
   "type": "stat",
   "description": "In TX. Holds back VACUUM. 1 million warning threshold",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time({__name__=~\"(pgwatch3_backends_max_xmin_age_tx|replication_slots_xmin_age_tx)\",dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Replication lag (max.)",
   "type": "stat",
   "description": "\"Apply\" (data made visible to queries on replica)  lag in bytes",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch3_replication_replay_lag_b{dbname='$dbname'}[$__range]))"
    }
   ]
  },
  {
   "title": "Inactive repl. slots",
   "type": "stat",
   "description": "Inactive repl. slots accumulate WAL files until disk space runs out. Re-animate the replica or use  pg_drop_replication_slot() to remove the slot so that Postgres can delete the un-needed WALs.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgwatch3_replication_slots_non_active_int{dbname='$dbname'})"
    }
   ]
  }
 ]
}