version: 2

before:
  hooks:
    # weirdly goreleaser doesn't all to include outside of the Go build "root" so need to copy
    - cp -r grafana ./src/
    - sh -c "cd ./src/webui && yarn install && yarn build"

builds:
- dir: src
  binary: pgwatch
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64

archives:
- name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - ./grafana/**/*
    - ./src/metrics/metrics.yaml
    - ./src/config/**/*
    - ./README.md

checksum:
  name_template: 'checksums.txt'

nfpms:
  # note that this is an array of nfpm configs
  -
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

    vendor: CYBERTEC PostgreSQL International GmbH
    homepage: https://github.com/cybertec-postgresql/pgwatch

    maintainer: Pavlo Golub <open.an.issue@github.com>
    description: pgwatch metrics collector with metric definitions and sample YAML config

    license: MIT Licence

    formats:
      - deb
      - rpm

    contents:
      - src: "./src/metrics/metrics.yaml"
        dst: "/etc/pgwatch/metrics.yaml"
        type: config
      - src: "./src/config/*"
        dst: "/etc/pgwatch/config"
        type: config
      - src: "./grafana/*"
        dst: "/etc/pgwatch/grafana"
      - src: "./README.md"
        dst: "/etc/pgwatch/README.md"
