version: 2

before:
  hooks:
    - sh -c "cd ./internal/webui && yarn install && yarn build"

builds:
- main: ./cmd/pgwatch
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64

archives:
- name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      formats: ['zip']
  files:
    - "./grafana/**/*"
    - "./README.md"
    - src: "./internal/metrics/metrics.yaml"
      dst: "metrics.yaml"
    - src: "./contrib/sample.sources.yaml"
      dst: "sample.sources.yaml"
    - src: "./contrib/sample.systemd.service"
      dst: "/etc/pgwatch/sample.systemd.service"


checksum:
  name_template: 'checksums.txt'

nfpms:
  # note that this is an array of nfpm configs
  -
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

    vendor: CYBERTEC PostgreSQL International GmbH
    homepage: https://github.com/cybertec-postgresql/pgwatch

    maintainer: Pavlo Golub <open.an.issue@github.com>
    description: pgwatch metrics collector with metric definitions and sample YAML config

    license: MIT Licence

    formats:
      - deb
      - rpm

    contents:
      - src: "./grafana/*"
        dst: "/etc/pgwatch/grafana"
      - src: "./contrib/sample.sources.yaml"
        dst: "/etc/pgwatch/sample.sources.yaml"
      - src: "./internal/metrics/metrics.yaml"
        dst: "/etc/pgwatch/metrics.yaml"
      - src: "./README.md"
        dst: "/etc/pgwatch/README.md"
      - src: "./contrib/sample.systemd.service"
        dst: "/etc/pgwatch/sample.systemd.service"
