# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # weirdly goreleaser doesn't all to include outside of the Go build "root" so need to copy
    - cp -r grafana_dashboards ./src/
    - cp -r webpy ./src/

builds:
  - dir: src
    binary: pgwatch3-daemon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  -
    # Archive name template.
    # Defaults:
    # - if format is `tar.gz`, `gz` or `zip`:
    #   - `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    # - if format is `binary`:
    #   - `{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Replacements for GOOS and GOARCH in the archive name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      amd64: 64-bit

    # Set to true, if you want all files in the archive to be in a single directory.
    # If set to true and you extract the archive 'goreleaser_Linux_arm64.tar.gz',
    # you get a folder 'goreleaser_Linux_arm64'.
    # If set to false, all files are extracted separately.
    # You can also set it to a custom folder name (templating is supported).
    # Default is false.
    wrap_in_directory: true

    # Archive format. Valid options are `tar.gz`, `gz`, `zip` and `binary`.
    # If format is `binary`, no archives are created and the binaries are instead
    # uploaded directly.
    # Default is `tar.gz`.
    format: tar.gz

    # Additional files/globs you want to add to the archive.
    # Defaults are any files matching `LICENCE*`, `LICENSE*`,
    # `README*` and `CHANGELOG*` (case-insensitive).
    files:
      - ./grafana_dashboards/**/*
      - ./webpy/**/*
      - ./src/metrics/**/*
      - ./src/config/**/*
      - ./src/sql/**/*
      - ./src/startup-scripts/**/*
      - ./src/bootstrap/**/*
      - ./README.md

nfpms:
  -
    # You can change the name of the package.
    # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      amd64: 64-bit

    # Your app's vendor.
    # Default is empty.
    vendor: CYBERTEC PostgreSQL International GmbH
    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/cybertec-postgresql/pgwatch3
    maintainer: Pavlo Golub <open.an.issue@github.com>

    # Your app's description.
    # Default is empty.
    description: pgwatch3 metrics collector with metric definitions and sample YAML config

    # Your app's license.
    # Default is empty.
    license: BSD 3-Clause License

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Packages your package depends on.
    dependencies:

    # Packages your package recommends installing.
    # For RPM packages rpmbuild >= 4.13 is required
    recommends:

    # Packages your package suggests installing.
    # For RPM packages rpmbuild >= 4.13 is required
    suggests:

    # Packages that conflict with your package.
    conflicts:

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

    # Empty folders that should be created and managed by the packager
    # implementation.
    # Default is empty.
    empty_folders:
      - /etc/pgwatch3

    # Files or directories to add to your package (beyond the binary).
    # Keys are source paths/globs to get the files from.
    # Values are the destination locations of the files in the package.
    contents:
      - src: "./pgwatch3/metrics/*"
        dst: "/etc/pgwatch3/metrics"
        type: config
      - src: "./pgwatch3/config/*"
        dst: "/etc/pgwatch3/config"
        type: config
      - src: "./pgwatch3/sql/*"
        dst: "/etc/pgwatch3/sql"
      - src: "./pgwatch3/bootstrap/*"
        dst: "/etc/pgwatch3/bootstrap"
      - src: "./pgwatch3/startup-scripts/pgwatch3.service"
        dst: "/etc/pgwatch3/startup-scripts/pgwatch3.service"
      - src: "./grafana_dashboards/*"
        dst: "/etc/pgwatch3/grafana-dashboards"
      - src: "./pgwatch3/webpy/*"
        dst: "/etc/pgwatch3/webpy"
      - src: "./README.md"
        dst: "/etc/pgwatch3/README.md"
