{
 "title": "1. Global Database Overview",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname\nFROM admin.all_distinct_dbname_metrics\nWHERE '$replicas' = 'show' OR dbname NOT IN (\n  SELECT dbname FROM (\n    SELECT\n      dbname,\n      (data->>'in_recovery_int')::int AS in_recovery_int,\n      ROW_NUMBER() OVER (PARTITION BY dbname ORDER BY time DESC) AS rn\n    FROM postgres_role\n    WHERE $__timeFilter(time)\n  ) sub\n  WHERE rn = 1 AND in_recovery_int = 2\n)\nORDER BY 1;\n"
   },
   { "name": "agg_interval", "query": "10s,1m,5m,1h" },
   { "name": "replicas", "query": "show, hide" }
  ]
 },
 "panels": [
  {
   "title": "Connections Overview",
   "type": "timeseries",
   "description": "Number of new database sessions established per monitored source over time. Each line represents a different monitored database/source.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with session_changes as (\r\n  SELECT \r\n  dbname,\r\n  time,\r\n  coalesce((data->>'sessions')::int8 - lag((data->>'sessions')::int8) over w, 0) as established\r\nfrom db_stats \r\nwhere dbname in ($dbname) and $__timeFilter(time)\r\nwindow w as (partition by dbname order by time)\r\n)\r\nselect \r\n  $__timeGroup(time, $agg_interval),\r\n  sum(established) as value,\r\n  dbname as metric\r\nfrom session_changes\r\ngroup by 1, dbname\r\norder by 1, dbname"
    }
   ]
  },
  {
   "title": "QPS (queries per second)",
   "type": "timeseries",
   "description": "Based on pg_stat_statements.calls",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \" \"\nfrom (\n  select \n    (data->>'calls')::bigint as c, lag((data->>'calls')::bigint) over w as c_lag,\n    time, lag(time) over w as time_lag, dbname\n  from stat_statements_calls\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname order by time)        \n) x\nwhere c > c_lag and time > time_lag\ngroup by 1, 2\norder by 1\n"
    }
   ]
  },
  {
   "title": "TPS (transactions per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg(((c - c_lag) + (r - r_lag)) / extract(epoch from time - time_lag)) as \" \"\nfrom (\n  select \n    (data->>'xact_commit')::bigint as c, lag((data->>'xact_commit')::bigint) over w as c_lag,\n    (data->>'xact_rollback')::bigint as r, lag((data->>'xact_rollback')::bigint) over w as r_lag,\n    time, lag(time) over w as time_lag, dbname\n  from db_stats\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname order by time)        \n) x\nwhere time > time_lag\n  and (c - c_lag) + (r - r_lag) > 0\ngroup by 1, 2\norder by 1\n"
    }
   ]
  },
  {
   "title": "Average query runtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((tt - tt_lag) / (c - c_lag)) as \" \"\nfrom (\n  select \n    (data->>'total_time')::numeric as tt, lag((data->>'total_time')::numeric) over w as tt_lag,\n    (data->>'calls')::bigint as c, lag((data->>'calls')::bigint) over w as c_lag,\n    time, dbname\n  from stat_statements\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname, (tag_data->>'queryid')::text order by time)\n) x\nwhere c > c_lag and tt > tt_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Total sessions (numbackends)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'numbackends')::bigint) as \" \"\nfrom db_stats\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'numbackends')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Longest transaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'longest_tx_seconds')::bigint) as \" \"\nfrom backends\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'longest_tx_seconds')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "description": "active — backend is currently active",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'active')::bigint) as \" \"\nfrom backends\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'active')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Exclusive locks (count)",
   "type": "timeseries",
   "description": "Based on pg_locks\n\nExclusiveLock, RowExclusiveLock, ShareRowExclusiveLock, AccessExclusiveLock, ShareUpdateExclusiveLock",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  sum((data->>'count')::bigint) as \" \"\nfrom locks_mode\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (tag_data->>'lockmode')::text ~~ '%Exclusive%'\n  and (data->>'count')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Waiting sessions",
   "type": "timeseries",
   "description": "waiting — backend is currently waiting on a lock",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'waiting')::numeric) as \" \"\nfrom backends\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'waiting')::numeric > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Rollbacks (TX error)",
   "type": "timeseries",
   "description": "xact_rollback - number of transactions in this database that have been rolled back",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((r - r_lag)::numeric / extract(epoch from time - time_lag)) as \" \"\nfrom (\n  select\n    (data->>'xact_rollback')::bigint as r,\n    lag((data->>'xact_rollback')::bigint) over w as r_lag,\n    time,\n    lag(time) over w as time_lag,\n    dbname\n  from db_stats\n  where dbname in ($dbname)\n    and $__timeFilter(time)\n  window w as (partition by dbname order by time)\n) x\nwhere time > time_lag\n  and (r - r_lag) >= 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Idle-in-transaction sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'idleintransaction')::bigint) as \" \"\nfrom backends\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'idleintransaction')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Shared buffer hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg(((h - h_lag)::numeric / ((h - h_lag) + (r - r_lag)))) as \" \"\nfrom (\n  select \n    (data->>'blks_hit')::bigint as h, lag((data->>'blks_hit')::bigint) over w as h_lag,\n    (data->>'blks_read')::bigint as r, lag((data->>'blks_read')::bigint) over w as r_lag,\n    time, dbname\n  from db_stats\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname order by time)\n) x\nwhere (h - h_lag) + (r - r_lag) > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Temp bytes written (1s rate)",
   "type": "timeseries",
   "description": "Amount of data written to temporary files by queries in this database.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((b - b_lag)::numeric / extract(epoch from time - time_lag)) as \" \"\nfrom (\n  select \n    (data->>'temp_bytes')::bigint as b, lag((data->>'temp_bytes')::bigint) over w as b_lag,\n    time, lag(time) over w as time_lag, dbname\n  from db_stats\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname order by time)\n) x\nwhere b > b_lag and time > time_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "WAL rate (1s rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((l - l_lag) / extract(epoch from time - time_lag)) as \" \"\nfrom (\n  select \n    (data->>'xlog_location_b')::numeric as l, lag((data->>'xlog_location_b')::numeric) over w as l_lag,\n    time, lag(time) over w as time_lag, dbname\n  from wal\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname order by time)\n) x\nwhere time > time_lag\n  and l > l_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Database IO time (1s rate)",
   "type": "timeseries",
   "description": "Time spent reading and writing data file blocks by backends in this database.\n\nBased on pg_stat_database. Requires \"track_io_timing=on\"",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg(((r - r_lag) + (w - w_lag)) / extract(epoch from time - time_lag)) as \" \"\nfrom (\n  select \n    (data->>'blk_read_time')::numeric as r, lag((data->>'blk_read_time')::numeric) over w as r_lag,\n    (data->>'blk_write_time')::numeric as w, lag((data->>'blk_write_time')::numeric) over w as w_lag,\n    time, lag(time) over w as time_lag, dbname\n  from db_stats\n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname order by time)\n) x\nwhere time > time_lag\n  and (r - r_lag) + (w - w_lag) > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "WAL Archive (pending_count)",
   "type": "timeseries",
   "description": "archiver_pending_count - number of WAL files in the archive queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'archiver_pending_count')::bigint) as \" \"\nfrom archiver_pending_count\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'archiver_pending_count')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Replication lag (byte)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  tag_data->>'application_name'::text as client_info,\n  avg((data->>'replay_lag_b')::bigint) as \" \"\nfrom replication\nwhere dbname in ($dbname) and $__timeFilter(time)\n  and (data->>'replay_lag_b')::bigint > 0\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->>'size_b')::bigint) as \" \"\nfrom db_size\nwhere dbname in ($dbname) and $__timeFilter(time)\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "PostgreSQL Role",
   "type": "timeseries",
   "description": "1 = Primary - accepting writes.\n\n2 = Secondary - read-only.\n\n0 = No Replication - physical replication is not configured or there are no available standby servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "select distinct\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  last_value((data->>'in_recovery_int')::bigint) over w as \" \"\nfrom postgres_role\nwhere dbname in ($dbname) and $__timeFilter(time)\nwindow w as (partition by dbname order by time)\norder by 1"
    }
   ]
  },
  {
   "title": "Wraparound: Multixact ID age",
   "type": "timeseries",
   "description": "mxid_age - Multixact ID age",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "rawSql": "/* select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  last((data->>'datminmxid_age')::bigint, time) as \" \"\nfrom datfrozenxid\nwhere dbname in ($dbname) and $__timeFilter(time)\ngroup by 1, 2\norder by 1 */\n\nSELECT\n  time,\n  dbname,\n  last_datminmxid_age AS \" \"\nFROM (\n  SELECT DISTINCT ON (dbname, time)\n    dbname,\n    $__timeGroup(time, $agg_interval),\n    (data->>'datminmxid_age')::bigint AS last_datminmxid_age\n  FROM datfrozenxid\n  WHERE dbname IN ($dbname)\n    AND $__timeFilter(time)\n  ORDER BY dbname, time DESC\n) sub\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Wraparound: Transaction ID age",
   "type": "timeseries",
   "description": "xid_age - Transaction ID age.\n\nOldest non-frozen tx age.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\",\n  dbname,\n  last_datfrozenxid_age as \" \"\nFROM\n  (\n    SELECT\n      DISTINCT ON (dbname, \"time\") dbname,\n      $__timeGroup(time, $agg_interval),\n      (data ->> 'datfrozenxid_age') :: bigint AS last_datfrozenxid_age\n    FROM\n      datfrozenxid\n    WHERE\n      dbname IN ($dbname)\n      AND $__timeFilter(time)\n    ORDER BY\n      dbname,\n      time DESC\n  ) sub\nORDER BY\n  \"time\";"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 77 },
   "options": {
    "content": "## Brought to you by\n\n<a href=\"https://www.cybertec-postgresql.com/en/\">\n  <img src=\"https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg\" alt=\"Cybertec – The PostgreSQL Database Company\" width=\"600\" />\n</a>"
   }
  }
 ]
}