{
 "title": "5. Table Details",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "Monitored Source",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'table_stats' ORDER BY 1;"
   },
   {
    "name": "table_full_name",
    "label": "Table Full Name",
    "query": "SELECT DISTINCT tag_data->>'table_full_name' FROM table_stats WHERE time > current_date-3 AND dbname = '$dbname' ORDER BY 1"
   },
   { "name": "agg_interval", "label": "Aggregation Interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" },
   { "name": "lag_interval", "label": "Lag Interval", "query": "1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  { "title": "Table Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Table Size",
   "type": "timeseries",
   "description": "Size of the table including all indexes and TOAST data",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "total_relation_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "query": "SELECT mean(\"total_relation_size_b\") FROM \"table_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  avg((data->>'table_size_b')::int8) as table_size,\n  avg((data->>'total_relation_size_b')::int8) as total_relation_size,\n  avg((data->>'toast_size_b')::int8) as toast_size\nFROM\n  table_stats\nWHERE\n  $__timeFilter(time) AND dbname = '$dbname'\n  AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\nGROUP BY 1\nORDER BY 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Table Scans",
   "type": "timeseries",
   "description": "Sequential and index scans performed on the table (1h rate, aggregated by interval)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "seq_scans",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "WITH last_out_of_range_row_time(time) AS (\n    SELECT time \n    FROM table_stats\n    WHERE dbname = '$dbname' AND time < $__timeFrom()::timestamptz\n    ORDER BY time DESC\n    LIMIT 1\n)\n\nSELECT\n  $__timeGroup(time, $agg_interval),\n  avg( ((seq_scan-seq_scan_lag)::numeric*3600) / extract(epoch from time - time_lag) ) as seq_scan,\n  avg( ((idx_scan-idx_scan_lag)::numeric*3600) / extract(epoch from time - time_lag) ) as idx_scan\nFROM (  \n  SELECT\n    (data->>'seq_scan')::int8 as seq_scan, lag((data->>'seq_scan')::int8) over w as seq_scan_lag,\n    (data->>'idx_scan')::int8 as idx_scan, lag((data->>'idx_scan')::int8) over w as idx_scan_lag,\n    time, lag(time) over w as time_lag  \n  FROM\n    table_stats\n  WHERE \n    time <= $__timeTo()::timestamptz AND time >= (SELECT time FROM last_out_of_range_row_time)\n    AND dbname = '$dbname' AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE seq_scan >= seq_scan_lag and time > time_lag\nGROUP BY 1\nORDER BY 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Modifications",
   "type": "timeseries",
   "description": "Insert, Update, and Delete operations on the table (1h rate, aggregated by interval)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "INS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_stats",
     "rawSql": "WITH last_out_of_range_row_time(time) AS (\n    SELECT time \n    FROM table_stats\n    WHERE dbname = '$dbname' AND time < $__timeFrom()::timestamptz\n    ORDER BY time DESC\n    LIMIT 1\n)\n\nselect\n  $__timeGroup(time, $agg_interval),\n  avg((ins-ins_lag) * 3600 / extract(epoch from time - time_lag)) as \"INSERT\",\n  avg((upd-upd_lag) * 3600 / extract(epoch from time - time_lag)) as \"UPDATE\",\n  avg((del-del_lag) * 3600 / extract(epoch from time - time_lag)) as \"DELETE\"\nfrom (\n        select \n          (data->>'n_tup_ins')::int8 as ins, lag((data->>'n_tup_ins')::int8) over w as ins_lag,\n          (data->>'n_tup_upd')::int8 as upd, lag((data->>'n_tup_upd')::int8) over w as upd_lag,\n          (data->>'n_tup_del')::int8 as del, lag((data->>'n_tup_del')::int8) over w as del_lag,\n          time, lag(time) over w as time_lag\n        from table_stats\n        where \n          time <= $__timeTo()::timestamptz AND time >= (SELECT time FROM last_out_of_range_row_time)\n          AND dbname = '$dbname' and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere ins >= ins_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffer Hit Rates",
   "type": "timeseries",
   "description": "Cache hit rates for heap, index, and TOAST data (aggregated by interval)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Heap",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "table_io_stats",
     "query": "SELECT non_negative_derivative(mean(\"heap_blks_hit\"), 10s) /  (non_negative_derivative(mean(\"heap_blks_hit\"), 10s) + non_negative_derivative(mean(\"heap_blks_read\"), 10s)) * 100 FROM \"table_io_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND \"table_full_name\" =~ /^$table_full_name$/ AND $timeFilter GROUP BY time($__interval) fill(none)",
     "rawSql": "WITH last_out_of_range_row_time(time) AS (\n  SELECT time \n  FROM table_io_stats\n  WHERE dbname = '$dbname' AND time < $__timeFrom()::timestamptz\n  ORDER BY time DESC\n  LIMIT 1\n)\n\nselect\n  $__timeGroup(time, $agg_interval),\n  avg( case when hh = hh_lag and hr = hr_lag then null else (hh-hh_lag)::numeric * 100 / (hh-hh_lag+hr-hr_lag) end ) as \"Heap\",\n  avg( case when ih = ih_lag and ir = ir_lag then null else (ih-ih_lag)::numeric * 100 / (ih-ih_lag+ir-ir_lag) end ) as \"Indexes\"  \nfrom (\n        select \n          (data->>'heap_blks_hit')::int8 as hh, lag((data->>'heap_blks_hit')::int8) over w as hh_lag,\n          (data->>'heap_blks_read')::int8 as hr, lag((data->>'heap_blks_read')::int8) over w as hr_lag,\n          (data->>'idx_blks_hit')::int8 as ih, lag((data->>'idx_blks_hit')::int8) over w as ih_lag,\n          (data->>'idx_blks_read')::int8 as ir, lag((data->>'idx_blks_read')::int8) over w as ir_lag,\n          time\n        from table_io_stats\n        where\n          time <= $__timeTo()::timestamptz AND time >= (SELECT time FROM last_out_of_range_row_time)\n          AND dbname = '$dbname' and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hh >= hh_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" },
      { "condition": "AND", "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Scan Activity",
   "type": "timeseries",
   "description": "Index scans per individual index (1h rate, aggregated by interval)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_index_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "index_stats",
     "rawSql": "WITH last_out_of_range_row_time(time) AS (\n  SELECT time \n  FROM index_stats\n  WHERE dbname = '$dbname' AND time < $__timeFrom()::timestamptz\n  ORDER BY time DESC\n  LIMIT 1\n)\n\nselect\n  $__timeGroup(time, $agg_interval),\n  index_name,\n  avg( ((idx_scan - idx_scan_lag)::numeric * 3600) / extract(epoch from time - time_lag) )\nfrom (\n        select \n          (data->>'idx_scan')::int8 as idx_scan, lag((data->>'idx_scan')::int8) over w as idx_scan_lag,\n          tag_data->>'index_name' as index_name,\n          time, lag(time) over w as time_lag\n        from index_stats\n        where\n          time <= $__timeTo()::timestamptz AND time >= (SELECT time FROM last_out_of_range_row_time)\n          AND dbname = '$dbname' and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere idx_scan >= idx_scan_lag and time > time_lag\ngroup by 1, 2\norder by 1, 2",
     "tags": [
      { "key": "table_full_name", "operator": "=~", "value": "/^$table_full_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Last VACUUM",
   "type": "stat",
   "description": "Time since last VACUUM including manual and AUTOVACUUM (1 month warning, 2 month error threshold)",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  (data->>'seconds_since_last_vacuum')::int8\nFROM\n  table_stats\nWHERE\n  $__timeFilter(time)\n  AND dbname  = '$dbname'\n  AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Last ANALYZE",
   "type": "stat",
   "description": "Time since last ANALYZE including manual and auto-ANALYZE (1 month warning, 2 month error threshold)",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  (data->>'seconds_since_last_analyze')::int8\nFROM\n  table_stats\nWHERE\n  $__timeFilter(time)\n AND dbname = '$dbname'\n  AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Time Lag Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "INSERT Operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(ins-ins_lag) as \"INSERT\"\nfrom (\n        select \n          (data->>'n_tup_ins')::int8 as ins,\n          lag((data->>'n_tup_ins')::int8) over w as ins_lag,\n          time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and $__timeFilter(time)\n        window w as (order by time)\n\n) x\nwhere ins >= ins_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(ins-ins_lag) as \"INSERT-$lag_interval\"\nfrom (\n        select \n          (data->>'n_tup_ins')::int8 as ins,\n          lag((data->>'n_tup_ins')::int8) over w as ins_lag,\n          time + '$lag_interval'::interval as time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        window w as (order by time)\n\n) x\nwhere ins >= ins_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "UPDATE Operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 319 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(upd-upd_lag) as \"UPDATE\"\nfrom (\n        select \n          (data->>'n_tup_upd')::int8 as upd,\n          lag((data->>'n_tup_upd')::int8) over w as upd_lag,\n          time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and $__timeFilter(time)\n        window w as (order by time)\n\n) x\nwhere upd >= upd_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(upd-upd_lag) as \"UPDATE-$lag_interval\"\nfrom (\n        select \n          (data->>'n_tup_upd')::int8 as upd,\n          lag((data->>'n_tup_upd')::int8) over w as upd_lag,\n          time + '$lag_interval'::interval as time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        window w as (order by time)\n\n) x\nwhere upd >= upd_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "DELETE Operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(del-del_lag) as \"DELETE\"\nfrom (\n        select \n          (data->>'n_tup_del')::int8 as del,\n          lag((data->>'n_tup_del')::int8) over w as del_lag,\n          time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and $__timeFilter(time)\n        window w as (order by time)\n\n) x\nwhere del >= del_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  sum(del-del_lag) as \"DELETE-$lag_interval\"\nfrom (\n        select \n          (data->>'n_tup_del')::int8 as del,\n          lag((data->>'n_tup_del')::int8) over w as del_lag,\n          time + '$lag_interval'::interval as time\n        from\n          table_stats\n        where\n          dbname = '$dbname'\n          and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n          and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        window w as (order by time)\n\n) x\nwhere del >= del_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Sequential Scans",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 337 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(seq_scan-seq_scan_lag) as seq_scan\nFROM (  \n  SELECT\n    (data->>'seq_scan')::int8 as seq_scan, lag((data->>'seq_scan')::int8) over w as seq_scan_lag,\n    time\n  FROM\n    table_stats\n  WHERE\n    $__timeFilter(time) AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE seq_scan >= seq_scan_lag\nGROUP BY 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(seq_scan-seq_scan_lag) as \"seq_scan-$lag_interval\"\nFROM (  \n  SELECT\n    (data->>'seq_scan')::int8 as seq_scan, lag((data->>'seq_scan')::int8) over w as seq_scan_lag,\n    time + '$lag_interval'::interval as time\n  FROM\n    table_stats\n  WHERE\n    time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n    AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE seq_scan >= seq_scan_lag\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Index Scans",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 346 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(idx_scan-idx_scan_lag) as idx_scan\nFROM (  \n  SELECT\n    (data->>'idx_scan')::int8 as idx_scan, lag((data->>'idx_scan')::int8) over w as idx_scan_lag,\n    time\n  FROM\n    table_stats\n  WHERE\n    $__timeFilter(time) AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE idx_scan >= idx_scan_lag\nGROUP BY 1\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum(idx_scan-idx_scan_lag) as \"idx_scan-$lag_interval\"\nFROM (  \n  SELECT\n    (data->>'idx_scan')::int8 as idx_scan, lag((data->>'idx_scan')::int8) over w as idx_scan_lag,\n    time + '$lag_interval'::interval as time\n  FROM\n    table_stats\n  WHERE\n    time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n    AND dbname = '$dbname'\n    AND tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n  WINDOW w as (order by time)\n) x\nWHERE idx_scan >= idx_scan_lag\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Shared Buffers Hit Rate - Heap",
     "type": "timeseries",
     "description": "Hit rate for the main table excluding indexes and TOAST",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 355 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  avg( case when hh = hh_lag and hr = hr_lag then null else (hh-hh_lag)::numeric * 100 / (hh-hh_lag+hr-hr_lag) end ) as \"Heap hit\"\nfrom (\n        select \n          (data->>'heap_blks_hit')::int8 as hh, lag((data->>'heap_blks_hit')::int8) over w as hh_lag,\n          (data->>'heap_blks_read')::int8 as hr, lag((data->>'heap_blks_read')::int8) over w as hr_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hh >= hh_lag and hr >= hr_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  avg( case when hh = hh_lag and hr = hr_lag then null else (hh-hh_lag)::numeric * 100 / (hh-hh_lag+hr-hr_lag) end ) as \"Heap hit-$lag_interval\"\nfrom (\n        select \n          (data->>'heap_blks_hit')::int8 as hh, lag((data->>'heap_blks_hit')::int8) over w as hh_lag,\n          (data->>'heap_blks_read')::int8 as hr, lag((data->>'heap_blks_read')::int8) over w as hr_lag,\n          time +'$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hh >= hh_lag and hr >= hr_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Shared Buffers Hit Rate - Toast",
     "type": "timeseries",
     "description": "Hit rate for the main table excluding indexes and TOAST",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 364 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  100 * avg( case when tr = tr_lag and th = th_lag and tir = tir_lag and tih = tir_lag then null else (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0))::numeric / (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) end ) as \"Toast hit\"\nfrom (\n        select \n          (data->>'toast_blks_read')::int8 as tr, lag((data->>'toast_blks_read')::int8) over w as tr_lag,\n          (data->>'toast_blks_hit')::int8 as th, lag((data->>'toast_blks_hit')::int8) over w as th_lag,\n          (data->>'tidx_blks_read')::int8 as tir, lag((data->>'tidx_blks_read')::int8) over w as tir_lag,\n          (data->>'tidx_blks_hit')::int8 as tih, lag((data->>'tidx_blks_hit')::int8) over w as tih_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  100 * avg( case when tr = tr_lag and th = th_lag and tir = tir_lag and tih = tir_lag then null else (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0))::numeric / (coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) end ) as \"Toast hit-$lag_interval\"\nfrom (\n        select \n          (data->>'toast_blks_read')::int8 as tr, lag((data->>'toast_blks_read')::int8) over w as tr_lag,\n          (data->>'toast_blks_hit')::int8 as th, lag((data->>'toast_blks_hit')::int8) over w as th_lag,\n          (data->>'tidx_blks_read')::int8 as tir, lag((data->>'tidx_blks_read')::int8) over w as tir_lag,\n          (data->>'tidx_blks_hit')::int8 as tih, lag((data->>'tidx_blks_hit')::int8) over w as tih_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Block Bandwidth - Heap",
     "type": "timeseries",
     "description": "Block bandwidth for heap data (assuming 8k blocks)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 373 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(hh-hh_lag+hr-hr_lag) as \"Heap read\"\nfrom (\n        select \n          (data->>'heap_blks_hit')::int8 as hh, lag((data->>'heap_blks_hit')::int8) over w as hh_lag,\n          (data->>'heap_blks_read')::int8 as hr, lag((data->>'heap_blks_read')::int8) over w as hr_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hr >= hr_lag and hh >= hh_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(hh-hh_lag+hr-hr_lag) as \"Heap read-$lag_interval\"\nfrom (\n        select \n          (data->>'heap_blks_hit')::int8 as hh, lag((data->>'heap_blks_hit')::int8) over w as hh_lag,\n          (data->>'heap_blks_read')::int8 as hr, lag((data->>'heap_blks_read')::int8) over w as hr_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere hr >= hr_lag and hh >= hh_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Block Bandwidth - Indexes",
     "type": "timeseries",
     "description": "Block bandwidth for index data (assuming 8k blocks)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 382 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(ih-ih_lag+ir-ir_lag) as \"Idx read\"\nfrom (\n        select \n          (data->>'idx_blks_hit')::int8 as ih, lag((data->>'idx_blks_hit')::int8) over w as ih_lag,\n          (data->>'idx_blks_read')::int8 as ir, lag((data->>'idx_blks_read')::int8) over w as ir_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere ir >= ir_lag and ih >= ih_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(ih-ih_lag+ir-ir_lag) as \"Idx read-$lag_interval\"\nfrom (\n        select \n          (data->>'idx_blks_hit')::int8 as ih, lag((data->>'idx_blks_hit')::int8) over w as ih_lag,\n          (data->>'idx_blks_read')::int8 as ir, lag((data->>'idx_blks_read')::int8) over w as ir_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere ir >= ir_lag and ih >= ih_lag\ngroup by 1\norder by 1"
      }
     ]
    },
    {
     "title": "Block Bandwidth - Toast",
     "type": "timeseries",
     "description": "Block bandwidth for TOAST data (assuming 8k blocks)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 391 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) as \"Toast read\"\nfrom (\n        select \n          (data->>'toast_blks_read')::int8 as tr, lag((data->>'toast_blks_read')::int8) over w as tr_lag,\n          (data->>'toast_blks_hit')::int8 as th, lag((data->>'toast_blks_hit')::int8) over w as th_lag,\n          (data->>'tidx_blks_read')::int8 as tir, lag((data->>'tidx_blks_read')::int8) over w as tir_lag,\n          (data->>'tidx_blks_hit')::int8 as tih, lag((data->>'tidx_blks_hit')::int8) over w as tih_lag,\n          time\n        from table_io_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
      },
      {
       "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  8192 * sum(coalesce(th,0)-coalesce(th_lag,0) + coalesce(tr,0)-coalesce(tr_lag,0) + coalesce(tir,0)-coalesce(tir_lag,0) + coalesce(tih,0)-coalesce(tih_lag,0)) as \"Toast read-$lag_interval\"\nfrom (\n        select \n          (data->>'toast_blks_read')::int8 as tr, lag((data->>'toast_blks_read')::int8) over w as tr_lag,\n          (data->>'toast_blks_hit')::int8 as th, lag((data->>'toast_blks_hit')::int8) over w as th_lag,\n          (data->>'tidx_blks_read')::int8 as tir, lag((data->>'tidx_blks_read')::int8) over w as tir_lag,\n          (data->>'tidx_blks_hit')::int8 as tih, lag((data->>'tidx_blks_hit')::int8) over w as tih_lag,\n          time + '$lag_interval'::interval as time\n        from table_io_stats\n        where dbname = '$dbname'\n        and time between ($__timeFrom()::timestamptz - '$lag_interval'::interval) and ($__timeTo()::timestamptz - '$lag_interval'::interval)\n        and tag_data @> jsonb_build_object('table_full_name', '$table_full_name')\n        window w as (order by time)\n) x\nwhere th > th_lag or tih > tih_lag or tr > tr_lag or tir > tir_lag\ngroup by 1\norder by 1"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}