{
 "title": "Index overview",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "Source Name",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics ORDER BY 1;"
   },
   { "name": "top", "label": "Top", "query": "10,15,30,50,100" },
   { "name": "agg_interval", "label": "Aggregate Interval", "query": "5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Top $top biggest indexes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "WITH index_scan_changes AS (\n  SELECT\n    time,\n    dbname,\n    tag_data ->> 'index_full_name' AS index_full_name,\n    tag_data ->> 'table_full_name' AS table_full_name,\n    (data ->> 'idx_scan')::int8 - LEAD((data ->> 'idx_scan')::int8) OVER w AS idx_scans,\n    (data ->> 'index_size_b')::int8 AS index_size_b,\n    ROW_NUMBER() OVER w AS rn\n  FROM\n    index_stats\n  WHERE\n    dbname IN ($dbname)\n  WINDOW w AS (\n    PARTITION BY dbname,\n      tag_data ->> 'table_full_name',\n      tag_data ->> 'index_full_name'\n    ORDER BY time DESC\n  )\n),\ntotal_scans AS (\n  SELECT\n    dbname,\n    table_full_name,\n    index_full_name,\n    SUM(COALESCE(idx_scans, 0)) AS total_idx_scans,\n    MAX(index_size_b) FILTER (WHERE rn = 1) AS latest_index_size\n  FROM\n    index_scan_changes\n  WHERE\n    $__timeFilter(time)\n  GROUP BY\n    dbname, table_full_name, index_full_name\n)\nSELECT\n  dbname AS \"Source Name\",\n  index_full_name AS \"Index Name\",\n  table_full_name AS \"Table Name\",\n  latest_index_size AS \"Index Size\",\n  total_idx_scans AS \"Scans\"\nFROM\n  total_scans\nORDER BY\n  latest_index_size DESC\nLIMIT $top"
    }
   ]
  },
  {
   "title": "Top $top indexes by disk reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "with index_stats_changes as (\n  select\n  time,\n  dbname,\n  tag_data->>'index_full_name' as index_full_name,\n  coalesce((data->>'idx_blks_read')::int8 - lag((data->>'idx_blks_read')::int8) over w, 0) as blks_read\n  from index_stats \n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname, tag_data->>'index_full_name' order by time)\n), top_indexes as (\n  select\n    dbname,\n    index_full_name,\n    sum(blks_read) as total_blks_read\n  from index_stats_changes\n  group by dbname, index_full_name\n  order by total_blks_read desc\n  limit $top\n), blocks(size) as (\n  select (data->>'block_size')::int8\n  from settings\n  where time <= $__timeTo()\n  order by time desc\n  limit 1\n)\n\nselect \n  $__timeGroup(time, $agg_interval),\n  sum(blks_read) * (select size from blocks) as blks_read,\n  dbname || ' ' || index_full_name as metric\nfrom index_stats_changes\nwhere dbname in (select dbname from top_indexes)\nand index_full_name in (select index_full_name from top_indexes)\ngroup by 1, dbname, index_full_name\norder by 1, dbname, index_full_name"
    }
   ]
  },
  {
   "title": "Top $top indexes by cache hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "with index_stats_changes as (\n  select\n  time,\n  dbname,\n  tag_data->>'index_full_name' as index_full_name,\n  coalesce((data->>'idx_blks_hit')::int8 - lag((data->>'idx_blks_hit')::int8) over w, 0) as blks_hit\n  from index_stats \n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname, tag_data->>'index_full_name' order by time)\n), top_indexes as (\n  select\n    dbname,\n    index_full_name,\n    sum(blks_hit) as total_blks_hit\n  from index_stats_changes\n  group by dbname, index_full_name\n  order by total_blks_hit desc\n  limit $top\n), blocks(size) as (\n  select (data->>'block_size')::int8\n  from settings\n  where time <= $__timeTo()\n  order by time desc\n  limit 1\n)\n\nselect \n  $__timeGroup(time, $agg_interval),\n  sum(blks_hit) * (select size from blocks) as blks_hit,\n  dbname || ' ' || index_full_name as metric\nfrom index_stats_changes\nwhere dbname in (select dbname from top_indexes)\nand index_full_name in (select index_full_name from top_indexes)\ngroup by 1, dbname, index_full_name\norder by 1, dbname, index_full_name"
    }
   ]
  },
  {
   "title": "Top $top indexes by number of tuples read",
   "type": "timeseries",
   "description": "Tuples Read = Number of index entries returned by scans on this index",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with index_stats_changes as (\n  select\n  time,\n  dbname,\n  tag_data->>'index_full_name' as index_full_name,\n  coalesce((data->>'idx_tup_read')::int8 - lag((data->>'idx_tup_read')::int8) over w, 0) as tuples_read\n  from index_stats \n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname, tag_data->>'index_full_name' order by time)\n), top_indexes as (\n  select\n    dbname,\n    index_full_name,\n    sum(tuples_read) as total_tuples_read\n  from index_stats_changes\n  group by dbname, index_full_name\n  order by total_tuples_read desc\n  limit $top\n)\nselect \n  $__timeGroup(time, $agg_interval),\n  sum(tuples_read) as tuples_read,\n  dbname || ' ' || index_full_name as metric\nfrom index_stats_changes\nwhere dbname in (select dbname from top_indexes)\nand index_full_name in (select index_full_name from top_indexes)\ngroup by 1, dbname, index_full_name\norder by 1, dbname, index_full_name"
    }
   ]
  },
  {
   "title": "Top $top indexes by number of tuples fetched",
   "type": "timeseries",
   "description": "Tuples Fetched = Number of live rows fetched from the table by simple index scans using this index",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with index_stats_changes as (\n  select\n  time,\n  dbname,\n  tag_data->>'index_full_name' as index_full_name,\n  coalesce((data->>'idx_tup_fetch')::int8 - lag((data->>'idx_tup_fetch')::int8) over w, 0) as tuples_fetched\n  from index_stats \n  where dbname in ($dbname) and $__timeFilter(time)\n  window w as (partition by dbname, tag_data->>'index_full_name' order by time)\n), top_indexes as (\n  select\n    dbname,\n    index_full_name,\n    sum(tuples_fetched) as total_tuples_fetched\n  from index_stats_changes\n  group by dbname, index_full_name\n  order by total_tuples_fetched desc\n  limit $top\n)\nselect \n  $__timeGroup(time, $agg_interval),\n  sum(tuples_fetched) as tuples_fetched,\n  dbname || ' ' || index_full_name as metric\nfrom index_stats_changes\nwhere dbname in (select dbname from top_indexes)\nand index_full_name in (select index_full_name from top_indexes)\ngroup by 1, dbname, index_full_name\norder by 1, dbname, index_full_name"
    }
   ]
  },
  {
   "title": "Missing Indexes",
   "type": "table",
   "description": "Adding indexes can have unexpected performance effects, so ensure that you test them first to verify that the recommendation has the desired effect.\n\nRequires `reco_add_index` metric. \n\nColumn Guide:\n- **Sum. Avg Queries Exec Time**: the sum of the average execution time for all queries that should be optimized by this index.\n- **Affected Queries**: all affected query ids to investigate further\n- **Recommendation**: the recommended index ddl.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    dbname as \"Source Name\",\n    tag_data->>'object_name' AS \"Table Name\",\n    data->>'total_avg_exec_time' AS \"Sum. Avg Exec Time\",\n    data->>'affected_query_ids' AS \"Affected Queries\",\n    data->>'recommendation' AS \"Recommendation\"\nFROM recommendations \nWHERE \n  time in (\n    select max(time) \n    from recommendations \n    where time <= $__timeTo() AND dbname in ($dbname) and tag_data->>'reco_topic' = 'create_index' \n    group by dbname\n  )\n  AND dbname IN ($dbname) AND tag_data->>'reco_topic' = 'create_index' \nORDER BY (data->>'total_avg_exec_time')::float8 DESC"
    }
   ]
  },
  {
   "title": "Invalid indexes",
   "type": "table",
   "description": "Requires `reco_drop_index` metric.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  dbname as \"Source Name\",\n  tag_data->>'table_full_name' as \"Table Name\",\n  tag_data->>'object_name' as \"Index Name\",\n  (data->>'index_size_b')::int8 as \"Index size\"\nFROM\n  recommendations \nWHERE \n  time in (\n    select max(time) \n    from recommendations \n    where $__timeFilter(time) AND dbname in ($dbname) \n      and tag_data->>'reco_topic' = 'drop_index' and tag_data->>'issue_type' = 'invalid' \n    group by dbname\n  )\n  AND dbname IN ($dbname) AND tag_data->>'reco_topic' = 'drop_index' and tag_data->>'issue_type' = 'invalid'\n"
    }
   ]
  },
  {
   "title": "Unused indexes (Non-PK)",
   "type": "table",
   "description": "Before dropping indexes make sure they are not used on replicas, if having any. FYI - one could also adjust the default 0 threshold so that \"little used\" indexes are shown.\n\nRequires `reco_drop_index` metric.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  dbname as \"Source Name\",\n  tag_data->>'table_full_name' as \"Table Name\",\n  tag_data->>'object_name' as \"Index Name\",\n  (data->>'index_size_b')::int8 as \"Index size\",\n  0::int8 as \"Scans\"\nFROM\n  recommendations \nWHERE \n  time in (\n    select max(time) \n    from recommendations \n    where $__timeFilter(time) AND dbname in ($dbname) \n      and tag_data->>'reco_topic' = 'drop_index' and tag_data->>'issue_type' = 'unused' \n    group by dbname\n  )\n  AND dbname IN ($dbname) AND tag_data->>'reco_topic' = 'drop_index' and tag_data->>'issue_type' = 'unused'\n"
    }
   ]
  },
  {
   "title": "Duplicate Indexes",
   "type": "table",
   "description": "Requires `reco_drop_index` metric.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  dbname as \"Source Name\",\n  tag_data->>'table_full_name' as \"Table Name\",\n  (data->>'index_size_b')::int8 as \"Max Index size\",\n  data->>'duplicate_count' as \"Num of duplicates\",\n  data->>'oids' as \"OIDs\",\n  data->>'index_def' as \"Index def\"\nFROM\n  recommendations \nWHERE \n  time in (\n    select max(time) \n    from recommendations \n    where $__timeFilter(time) AND dbname in ($dbname) \n     and tag_data->>'reco_topic' = 'drop_index' and tag_data->>'issue_type' = 'duplicate' \n    group by dbname\n  )\n  AND dbname IN ($dbname) AND tag_data->>'reco_topic' = 'drop_index' and tag_data->>'issue_type' = 'duplicate'\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "## Brought to you by\n\n<a href=\"https://www.cybertec-postgresql.com/en/\">\n  <img src=\"https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg\" alt=\"Cybertec – The PostgreSQL Database Company\" width=\"600\" />\n</a>"
   }
  }
 ]
}