{
 "title": "PgBouncer stats",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "monitoredsource",
    "label": "Monitored Source",
    "query": "select dbname as monitoredsource from admin.all_distinct_dbname_metrics where metric = 'pgbouncer_stats';"
   },
   {
    "name": "databases",
    "label": "Databases",
    "query": "select distinct (data->>'database') as database from pgbouncer_stats where dbname = '$monitoredsource' and $__timeFilter(time);"
   }
  ]
 },
 "panels": [
  {
   "title": "TPS - $databases",
   "type": "stat",
   "description": "Current \"Transaction Per Second\" based on total_xact_count",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "repeat": "databases",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as tps\nfrom (\n        select \n          (data->>'total_xact_count')::int8 as c, lag((data->>'total_xact_count')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$databases$/" }
     ]
    }
   ]
  },
  {
   "title": "QPS - $databases",
   "type": "stat",
   "description": "Current \"Queries Per Second\" based on total_query_count",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "repeat": "databases",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as tps\nfrom (\n        select \n          (data->>'total_query_count')::int8 as c, lag((data->>'total_query_count')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$databases$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg. query runtime - $databases",
   "type": "stat",
   "description": "Current value based on derivative of total_query_time /  total_query_count",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "repeat": "databases",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "avg_query_runtime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\n$__timeGroup(time, $__interval),\navg((tt-tt_lag)::numeric / (c-c_lag))\n\nfrom (\n\n        select \n          (data->>'total_query_time')::float8 as tt, lag((data->>'total_query_time')::float8) over w as tt_lag,\n          (data->>'total_query_count')::int8 as c, lag((data->>'total_query_count')::int8) over w as c_lag,\n          time\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Pool wait time - $databases",
   "type": "stat",
   "description": "Current avg. wait time to get a connection, per query",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "repeat": "databases",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "db_size_change_last_hour",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n$__timeGroup(time, $__interval),\navg((tt-tt_lag)::numeric / (c-c_lag))\n\nfrom (\n\n        select \n          (data->>'total_wait_time')::float8 as tt, lag((data->>'total_wait_time')::float8) over w as tt_lag,\n          (data->>'total_query_count')::int8 as c, lag((data->>'total_query_count')::int8) over w as c_lag,\n          time\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$databases$/" }
     ]
    }
   ]
  },
  {
   "title": "Incoming traffic - $databases",
   "type": "stat",
   "description": "Current Incoming traffic  based on total_received.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "repeat": "databases",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bytes_received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as tps\nfrom (\n        select \n          (data->>'total_received')::int8 as c, lag((data->>'total_received')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$databases$/" }
     ]
    }
   ]
  },
  {
   "title": "Outgoing traffic - $databases",
   "type": "stat",
   "description": "Based on total_sent",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "repeat": "databases",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as tps\nfrom (\n        select \n          (data->>'total_sent')::int8 as c, lag((data->>'total_sent')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$databases$/" }
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Based on total_query_count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval), \n  database,\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"TPS\"\nfrom (\n        select \n          (data->>'total_xact_count')::int8 as c, lag((data->>'total_xact_count')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag, data->>'database' as database\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1, 2\norder by 1",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$databases$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool wait time per Query",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Pool wait time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "db_stats",
     "rawSql": "select\n$__timeGroup(time, $__interval),\ndatabase,\navg((tt-tt_lag)::numeric / (c-c_lag)) as \"Pool wait time\"\n\nfrom (\n\n        select \n          (data->>'total_wait_time')::float8 as tt, lag((data->>'total_wait_time')::float8) over w as tt_lag,\n          (data->>'total_query_count')::int8 as c, lag((data->>'total_query_count')::int8) over w as c_lag,\n          time, data->>'database' as database\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  database,\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"QPS\"\nfrom (\n        select \n          (data->>'total_query_count')::int8 as c, lag((data->>'total_query_count')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag, data->>'database' as database\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Incoming traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Incoming rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  database,\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"Incoming rate\"\nfrom (\n        select \n          (data->>'total_received')::int8 as c, lag((data->>'total_received')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag, data->>'database' as database\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Avg. query runtime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Avg. runtime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\n$__timeGroup(time, $__interval),\ndatabase,\navg((tt-tt_lag)::numeric / (c-c_lag)) as \"Avg. runtime\"\nfrom (\n\n        select \n          (data->>'total_query_time')::float8 as tt, lag((data->>'total_query_time')::float8) over w as tt_lag,\n          (data->>'total_query_count')::int8 as c, lag((data->>'total_query_count')::int8) over w as c_lag,\n          time,\n          data->>'database' as database\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "Outgoing traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Outgoing rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pgbouncer_stats",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  database,\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"Outgoing rate\"\nfrom (\n        select \n          (data->>'total_sent')::int8 as c, lag((data->>'total_sent')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag, data->>'database' as database\n        from pgbouncer_stats\n        where data->>'database' in (${databases:sqlstring}) and dbname = '$monitoredsource' and $__timeFilter(time)\n        window w as (order by data->>'database', time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}