{
 "title": "Recommendations",
 "description": "Needs \"recommendations\" metric to be enabled",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "Monitored Source",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics ORDER BY 1;"
   },
   {
    "name": "table_name",
    "query": "SELECT COALESCE (to_regclass('recommendations')::text, '(SELECT NULL time, NULL dbname, NULL::json data, NULL::jsonb tag_data WHERE false)')"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Recommendations",
   "type": "table",
   "description": "All database recommendations from automated analysis",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  dbname AS \"Source\",\n  tag_data->>'reco_topic' AS \"Category\",\n  tag_data->>'object_name' AS \"Objects\",\n  data->>'recommendation' AS \"Recommendation\",\n  data->>'extra_info' AS \"Additional Info\"\nFROM\n  $table_name\nWHERE\n  time IN (SELECT max(time) FROM $table_name WHERE $__timeFilter(time) GROUP BY dbname, tag_data->>'reco_topic')\n  AND dbname IN ($dbname)\n  AND tag_data->>'reco_topic' IS NOT NULL\nORDER BY\n  dbname, tag_data->>'reco_topic'"
    }
   ]
  },
  {
   "title": "Possible AUTOVACUUM problems",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  dbname AS \"Source\",\n  (SELECT (data->>'value')::int8::text FROM settings_num s WHERE s.dbname = x.dbname AND s.tag_data->>'name' = 'server_version_num' ORDER BY time DESC LIMIT 1) AS \"PostgreSQL Version\",\n  'AUTOVACUUM Workers' AS \"Category\",\n  'If most / all autovacuum worker slots are busy or AV runs for hours then this could hint at incorrect AV params or too much workload' AS \"Recommendation\",\n  'Max. active autovacuum workers: ' || max_av_workers || ' (of total ' || (SELECT (data->>'value')::int FROM settings_num s WHERE s.dbname = x.dbname AND s.tag_data->>'name' = 'autovacuum_max_workers' ORDER BY s.time DESC LIMIT 1) || '); Max. AV duration (seconds): ' || longest_autovacuum_seconds AS \"Additional Info\"\nFROM (\nSELECT\n  dbname,\n  max((data->>'av_workers')::int) as max_av_workers,\n  coalesce(max((data->>'longest_autovacuum_seconds')::int), 0) as longest_autovacuum_seconds\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  AND dbname IN ($dbname)\nGROUP BY\n  dbname\n) x\nWHERE\n  (max_av_workers > 1 AND max_av_workers::numeric / (SELECT (data->>'value')::int FROM settings_num s WHERE s.dbname = x.dbname AND s.tag_data->>'name' = 'autovacuum_max_workers' ORDER BY s.time DESC LIMIT 1)  >= 0.6)\n  OR\n  (longest_autovacuum_seconds > 1800)"
    }
   ]
  },
  {
   "title": "Longest query runtime",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  dbname AS \"Source\",\n  'Performance Issue' AS \"Category\",\n  'Long Running Queries' AS \"Objects\",\n  'Long running queries block autovacuum and thereby cause bloat' AS \"Recommendation\",\n  'Longest query duration: '|| max((data->>'longest_query_seconds')::int)::text || ' seconds' AS \"Additional Info\"\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  AND dbname IN ($dbname)\n  AND (data->>'longest_query_seconds')::int > 0\nGROUP BY\n  dbname\nORDER BY\n  max((data->>'longest_query_seconds')::int) DESC NULLS LAST, dbname"
    }
   ]
  },
  {
   "title": "Checkpoints requested too often",
   "type": "table",
   "description": "More often than checkpoint_timeout / 2. To improve increase checkpoint_timeout  or max_wal_size, which will reduce total IO amount done due to the way how Full Page Writes are handled.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  dbname AS \"Source\",\n  (SELECT (data->>'value')::int8::text FROM settings_num s WHERE s.dbname = y.dbname AND s.tag_data->>'name' = 'server_version_num' ORDER BY s.time DESC LIMIT 1) AS \"PostgreSQL Version\",\n  'Global Server Settings' AS \"Category\",\n  'Increase checkpoint_timeout or max_wal_size for more infrequent checkpoints, thereby reducing total IO' AS \"Recommendation\",\n  'Avg. seconds between checkpoint requests: ' || avg_seconds_between_checkpoints_reqs::int8 AS \"Additional Info\"\nFROM (\nSELECT\n  dbname,\n  round((extract(epoch from max_time - min_time) / (max_req - min_req))::numeric, 1) as avg_seconds_between_checkpoints_reqs\nFROM (\n  SELECT\n    dbname,\n    min(time) as min_time,\n    max(time) as max_time,\n    min((data->>'checkpoints_req')::int8) as min_req,\n    max((data->>'checkpoints_req')::int8) as max_req\n  FROM\n    bgwriter\n  WHERE\n    $__timeFilter(time)\n  AND dbname IN ($dbname)\nGROUP BY\n  dbname\nHAVING\n  max((data->>'checkpoints_req')::int8) > min((data->>'checkpoints_req')::int8)\n) x\n) y\nWHERE\n  avg_seconds_between_checkpoints_reqs < (SELECT (data->>'value')::float8 / 2.0 FROM settings_num s WHERE s.dbname = y.dbname AND s.tag_data->>'name' = 'checkpoint_timeout' ORDER BY s.time DESC LIMIT 1)\nORDER BY\n  avg_seconds_between_checkpoints_reqs\nLIMIT\n  25"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 35 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}