{
 "title": "Server Log Events",
 "description": "Works with csvlog, jsonlog or stderr, in local or remote mode",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'server_log_event_counts' ORDER BY 1;"
   },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Server log events (DB)",
   "type": "timeseries",
   "description": "Based on 'server_log_event_counts' metric. Works with csvlog, jsonlog or stderr, in local or remote mode",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum((data->>'debug')::int8) as debug,\n  sum((data->>'log')::int8) as log,\n  sum((data->>'notice')::int8) as notice,  \n  sum((data->>'warning')::int8) as warning,\n  sum((data->>'error')::int8) as error,\n  sum((data->>'fatal')::int8) as fatal,\n  sum((data->>'panic')::int8) as panic\nFROM\n  server_log_event_counts\nWHERE\n  $__timeFilter(time)\n  AND dbname in ($dbname)\nGROUP BY\n  1\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "Server log events (whole instance)",
   "type": "timeseries",
   "description": "Based on 'server_log_event_counts' metric. Works with csvlog, jsonlog or stderr, in local or remote mode",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  sum((data->>'debug_total')::int8) as debug,\n  sum((data->>'log_total')::int8) as log,\n  sum((data->>'notice_total')::int8) as notice,  \n  sum((data->>'warning_total')::int8) as warning,\n  sum((data->>'error_total')::int8) as error,\n  sum((data->>'fatal_total')::int8) as fatal,\n  sum((data->>'panic_total')::int8) as panic\nFROM\n  server_log_event_counts\nWHERE\n  $__timeFilter(time)\n  AND dbname in ($dbname)\nGROUP BY\n  1\nORDER BY\n  1\n"
    }
   ]
  },
  {
   "title": "Top ERROR generating DBs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  dbname,\n  sum((data->>'error')::int8) as \"ERROR\",\n  sum((data->>'error_total')::int8) as \"ERROR_TOTAL\",\n  sum((data->>'fatal')::int8) as \"FATAL\",  \n  sum((data->>'fatal_total')::int8) as \"FATAL_TOTAL\"\nFROM\n  server_log_event_counts\nWHERE\n  $__timeFilter(time)\n  AND dbname in ($dbname)\nGROUP BY\n  1\nORDER BY\n  2 DESC\nLIMIT\n  20\n"
    }
   ]
  },
  {
   "title": "Top FATAL generating instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  dbname,\n  sum((data->>'fatal_total')::int8) as \"FATAL_TOTAL\",\n  sum((data->>'fatal')::int8) as \"FATAL\",\n  sum((data->>'error_total')::int8) as \"ERROR_TOTAL\",\n  sum((data->>'error')::int8) as \"ERROR\"\nFROM\n  server_log_event_counts\nWHERE\n  $__timeFilter(time)\n  AND dbname in ($dbname)\nGROUP BY\n  1\nORDER BY\n  2 DESC\nLIMIT\n  20\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}