{
 "title": "Sessions overview",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'backends' ORDER BY 1;"
   },
   {
    "name": "agg_interval",
    "query": "1s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections Overview",
   "type": "timeseries",
   "description": "- Total number of sessions established to this database. \n- Number of database sessions to this database that were terminated because connection to the client was lost.\n- Number of database sessions to this database that were terminated by fatal errors.\n- Number of database sessions to this database that were terminated by operator intervention.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with sessions as (\r\n  SELECT \r\n  $__timeGroup(time, $agg_interval),\r\n  (data->>'sessions')::int8 as sessions,\r\n  lag((data->>'sessions')::int8) over w as lag_sessions,\r\n  (data->>'sessions_abandoned')::int8 as sessions_abandoned,\r\n  lag((data->>'sessions_abandoned')::int8) over w as lag_sessions_abandoned,\r\n  (data->>'sessions_fatal')::int8 as sessions_fatal,\r\n  lag((data->>'sessions_fatal')::int8) over w as lag_sessions_fatal,\r\n  (data->>'sessions_killed')::int8 as sessions_killed,\r\n  lag((data->>'sessions_killed')::int8) over w as lag_sessions_killed\r\nfrom db_stats \r\nwhere dbname = '$dbname' and $__timeFilter(time)\r\nwindow w as (order by time)\r\n)\r\nselect \r\n  time,\r\n  sum(sessions-lag_sessions) as established,\r\n  sum(sessions_abandoned-lag_sessions_abandoned) as abandoned,\r\n  sum(sessions_fatal-lag_sessions_fatal) as fatal,\r\n  sum(sessions_killed-lag_sessions_killed) as killed\r\nfrom sessions \r\ngroup by time\r\norder by 1"
    }
   ]
  },
  {
   "title": "Max. TPS / QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max(((c - c_lag) + (r - r_lag)) / extract(epoch from time - time_lag)) as \"TPS\"\nfrom (\n        select \n          (data->>'xact_commit')::int8 as c, lag((data->>'xact_commit')::int8) over w as c_lag,\n          (data->>'xact_rollback')::int8 as r, lag((data->>'xact_rollback')::int8) over w as r_lag,\n          time, lag(time) over w as time_lag\n        from db_stats\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)        \n) x\nwhere c >= c_lag and r >= r_lag and time > time_lag\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((c - c_lag) / extract(epoch from time - time_lag)) as \"QPS\"\nfrom (\n        select \n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag\n        from stat_statements_calls\n        where dbname = '$dbname' and $__timeFilter(time)\n        window w as (order by time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1\norder by 1\n"
    }
   ]
  },
  {
   "title": "Longest query duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'longest_query_seconds')::int8) as longest_query,\n  max((data->>'avg_query_seconds')::float) as avg_query\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Longest wait duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'longest_waiting_seconds')::int8) as longest_waiting,\n  max((data->>'avg_waiting_seconds')::float) as avg_waiting\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Longest TX duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'longest_tx_seconds')::int8) as longest_tx,\n  max((data->>'avg_tx_seconds')::float) as avg_tx\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Longest session duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'longest_session_seconds')::int8) as longest_session,\n  max((data->>'avg_session_seconds')::float) as avg_session\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Longest Autovacuum duration / # AV workers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'longest_autovacuum_seconds')::int8) as longest_autovacuum_seconds\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'av_workers')::int8) as max_av_workers\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Sessions by state",
   "type": "timeseries",
   "description": "Max. value per $agg_interval",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'active')::int8) as active,\n  max((data->>'total')::int8) as total_db,\n  max((data->>'idleintransaction')::int8) as idleintransaction,\n  max((data->>'waiting')::int8) as waiting\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Instance total connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  max((data->>'instance_total')::int8) as instance_total,\n  max((data->>'max_connections')::int8) as max_connections\nfrom backends\nwhere dbname = '$dbname' and $__timeFilter(time)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 56 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}