{
 "title": "Single query details",
 "description": "For one query",
 "tags": [ "pgwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "Database",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics WHERE metric = 'stat_statements' ORDER BY 1;"
   },
   { "name": "queryid", "label": "Query ID" },
   { "name": "agg_interval", "label": "Agg Interval", "query": "3m,6m,9m,12m,15m,30m" },
   {
    "name": "sql_text",
    "query": "select tag_data->>'query'\nfrom stat_statements\nwhere dbname = '$dbname'\n  and tag_data @> '{\"queryid\": \"$queryid\"}'\norder by time desc\nlimit 1"
   }
  ]
 },
 "panels": [
  { "title": "SQL", "type": "text", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 }, "options": { "content": "$sql_text" } },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "calls/s" } },
   "targets": [
    {
     "alias": "calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "rawSql": "with baseline AS (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  sum(c - c_lag) / nullif(extract(epoch from sum(time - time_lag)), 0) as \"calls_per_sec\"\nfrom (\n  select\n    (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n    time, lag(time) over w as time_lag\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere c >= c_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Execution time per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "alias": "avg_runtime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"total_time\")) / non_negative_derivative(mean(\"calls\")) FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(null)",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  sum(tt - tt_lag) / nullif(extract(epoch from sum(time - time_lag)), 0) as \"total_time_per_sec\"\nfrom (\n  select\n    (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,\n    time, lag(time) over w as time_lag\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere tt >= tt_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Execution time per call",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "avg_runtime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  avg(case when c = c_lag then null else (tt - tt_lag) / nullif(c - c_lag, 0) end) as \"time_per_call\"\nfrom (\n  select\n    (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n    (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,\n    time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere c >= c_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "sb_hit_ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"shared_blks_hit\")) / (non_negative_derivative(mean(\"shared_blks_hit\")) + non_negative_derivative(mean(\"shared_blks_read\"))) * 100 FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(null)",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  avg(case when hit = hit_lag and read = read_lag then null else ((hit-hit_lag)::numeric * 100) / nullif((hit-hit_lag) + (read-read_lag), 0) end) as \"sb_hit_ratio\"\nfrom (\n  select\n    (data->>'shared_blks_hit')::int8 as hit, lag((data->>'shared_blks_hit')::int8) over w as hit_lag,\n    (data->>'shared_blks_read')::int8 as read, lag((data->>'shared_blks_read')::int8) over w as read_lag,\n    time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere hit >= hit_lag and read >= read_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers Hit/Read per call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "sb_hit_ratio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "SELECT non_negative_derivative(mean(\"shared_blks_hit\")) / (non_negative_derivative(mean(\"shared_blks_hit\")) + non_negative_derivative(mean(\"shared_blks_read\"))) * 100 FROM \"stat_statements\" WHERE \"queryid\" =~ /^$queryid$/ AND $timeFilter GROUP BY time($__interval), \"queryid\" fill(null)",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n),\nbase_data as (\n  select\n    (data->>'shared_blks_hit')::int8 as hit, lag((data->>'shared_blks_hit')::int8) over w as hit_lag,\n    (data->>'shared_blks_read')::int8 as read, lag((data->>'shared_blks_read')::int8) over w as read_lag,\n    (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n    time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  avg(case when c = c_lag then null else ((hit - hit_lag)::numeric * 8192) / nullif(c - c_lag, 0) end) as \"Shared Buffers bytes hit\",\n  avg(case when c = c_lag then null else ((read - read_lag)::numeric * 8192) / nullif(c - c_lag, 0) end) as \"Shared Buffers bytes read\"\nfrom base_data\nwhere hit >= hit_lag and read >= read_lag and c >= c_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp Bytes Read/Written per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "temp_blks_written",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  sum(read - read_lag) * 8192 / nullif(extract(epoch from sum(time - time_lag)), 0) as \"Temp Bytes read\",\n  sum(written - written_lag) * 8192 / nullif(extract(epoch from sum(time - time_lag)), 0) as \"Temp Bytes written\"\nfrom (\n  select\n    (data->>'temp_blks_read')::int8 as read, lag((data->>'temp_blks_read')::int8) over w as read_lag,\n    (data->>'temp_blks_written')::int8 as written, lag((data->>'temp_blks_written')::int8) over w as written_lag,\n    time, lag(time) over w as time_lag\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere read >= read_lag and written >= written_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp Bytes Read/Written per call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "temp_blks_written",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  avg(case when c = c_lag then null else ((read - read_lag)::numeric * 8192) / nullif(c - c_lag, 0) end) as \"Temp Bytes read\",\n  avg(case when c = c_lag then null else ((written - written_lag)::numeric * 8192) / nullif(c - c_lag, 0) end) as \"Temp Bytes written\"\nfrom (\n  select\n    (data->>'temp_blks_read')::int8 as read, lag((data->>'temp_blks_read')::int8) over w as read_lag,\n    (data->>'temp_blks_written')::int8 as written, lag((data->>'temp_blks_written')::int8) over w as written_lag,\n    (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n    time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere read >= read_lag and written >= written_lag and c >= c_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend block Read/Write time",
   "type": "timeseries",
   "description": "FYI - blk_write_time can easily be 0 as normally changes happen only in the shared buffers and are written out by the checkpointer / background writer.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "alias": "blk_read_time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  sum(read - read_lag) / nullif(extract(epoch from sum(time - time_lag)), 0) as \"blk_read_time\",\n  sum(write - write_lag) / nullif(extract(epoch from sum(time - time_lag)), 0) as \"blk_write_time\"\nfrom (\n  select\n    (data->>'blk_read_time')::numeric as read, lag((data->>'blk_read_time')::numeric) over w as read_lag,\n    (data->>'blk_write_time')::numeric as write, lag((data->>'blk_write_time')::numeric) over w as write_lag,\n    time, lag(time) over w as time_lag\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere read >= read_lag and write >= write_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1",
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "% of total_time spent in direct IO ($agg_interval avg.)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "io_time_pct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "with baseline as (\n  select time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time < $__timeFrom()::timestamptz\n  order by time desc\n  limit 1\n)\nselect\n  $__timeGroup(time, $agg_interval),\n  avg(case when tt = tt_lag then null else (read - read_lag + write - write_lag)::numeric * 100 / nullif(tt - tt_lag, 0) end) as \"io_time_pct\"\nfrom (\n  select\n    (data->>'blk_read_time')::numeric as read, lag((data->>'blk_read_time')::numeric) over w as read_lag,\n    (data->>'blk_write_time')::numeric as write, lag((data->>'blk_write_time')::numeric) over w as write_lag,\n    (data->>'total_time')::numeric as tt, lag((data->>'total_time')::numeric) over w as tt_lag,\n    time\n  from stat_statements\n  where dbname = '$dbname'\n    and tag_data @> '{\"queryid\": \"$queryid\"}'\n    and time <= $__timeTo()::timestamptz\n    and time >= coalesce((select time from baseline), $__timeFrom()::timestamptz)\n  window w as (order by time)\n) x\nwhere read >= read_lag and write >= write_lag\n  and time >= $__timeFrom()::timestamptz\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 39 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://cdn.jsdelivr.net/gh/cybertec-postgresql/pgwatch@master/docs/gallery/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}