# Sets up a standard v12 Postgres cluster from PGDG repos + ensure a pgwatch3 monitoring role
# NB! Expects Ubuntu / Debian hosts currently!
# NB2! Although a trusted environment is assumed a password (perftesting) for the pgwatch3 (superuser!) user is set. Change accordingly

- hosts: all
  become: yes
  gather_facts: false

  tasks:

    - name: Configure postgresql.org official APT repo
      block:
        - shell: 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        - shell: 'wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -'

    - name: Install default Postgres + PL/Python
      apt:
        pkg:
          - postgresql-12
          - postgresql-plpython3-12
          - python3-psutil
        state: present
        update_cache: yes

    - name: Enable * access
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        line: |
          listen_addresses='*'
        state: present

    - name: Enable pg_stat_statements extension
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        line: |
          shared_preload_libraries='pg_stat_statements'
        state: present

    - name: Enable local trust access - remove default entry
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer$'
        state: absent

    - name: Enable local trust access
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        regexp: '^local\s+all\s+all\s+peer$'
        line: 'local all all trust'

    - name: Enable remote password access
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        line: 'host all all 0.0.0.0/0 md5'

    - name: Restart postgres
      systemd:
        name: postgresql
        state: restarted

    - name: Ensure pgwatch3 role. NB! Using superuser here which is not of course recommended generally for remote monitoring
      shell: 'createuser -U postgres --superuser -g pg_monitor pgwatch3'
      ignore_errors: yes

    - name: Set pgwatch3 password to "perftesting"
      shell:
        cmd: |
          psql -U postgres -c "alter role pgwatch3 password 'md56d9f217af43ed7b01c23fd48bfa3bb3f'"

    - name: Create the pg_stat_statements extension
      shell:
        cmd: |
          psql -U postgres -c "create extension if not exists pg_stat_statements"

    - name: Initialize a pgbench schema
      shell:
        cmd: |
          psql -U postgres -c "select count(*) from pgbench_branches" || pgbench -U postgres -i -s 10

    - name: Create a bunch of dummy tables to be more realistic
      shell:
        cmd: |
          for x in {1..100}; do PGOPTIONS="-c synchronous_commit=off" psql -U postgres -c "create table if not exists test_table_${x}(LIKE pgbench_accounts INCLUDING INDEXES)" ; done
        executable: /bin/bash

    - name: Ensure a background Cronjob that generates some light Postgres load so that one could even look a graphs
      cron:
        name: "pgbench"
        minute: "*/10"
        job: |
          pgbench -U postgres -R 1 -T 500 -N postgres >/dev/null
