{
 "title": "Global DB overview",
 "tags": [ "pgwatch3" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "current_primaries_only", "query": "yes,no" },
   {
    "name": "dbname",
    "query": "SELECT DISTINCT dbname FROM admin.all_distinct_dbname_metrics a WHERE case when '$current_primaries_only' = 'yes' then (select (data->'in_recovery_int')::int as in_recovery_int from db_stats where dbname = a.dbname and time > now() - '1h'::interval order by time desc limit 1) = 0 else true end ORDER BY 1;"
   },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "singlestat",
   "description": "Avg. of all DBs over the whole selected period",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(tx) from (SELECT non_negative_derivative(mean(\"xact_commit\"), 1s) + non_negative_derivative(mean(\"xact_rollback\"), 1s) as tx FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY dbname, time(5m) fill(none))",
     "rawSql": "select\n  time,\n  sum(avg) as tps\nfrom (\nselect\n  $__timeGroup(time, $__interval),\n  dbname,\n  avg(((c - c_lag) + (r - r_lag)) / extract(epoch from time - time_lag))\nfrom (\n        select\n          (data->>'xact_commit')::int8 as c, lag((data->>'xact_commit')::int8) over w as c_lag,\n          (data->>'xact_rollback')::int8 as r, lag((data->>'xact_rollback')::int8) over w as r_lag,\n          time, lag(time) over w as time_lag,\n          dbname\n        from db_stats\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)        \n) x\nwhere c >= c_lag and r >= r_lag and time > time_lag\ngroup by 1, 2\n) y\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "description": "Avg. of all DBs over the whole selected period",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "alias": "QPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(calls) FROM (SELECT non_negative_derivative(mean(\"calls\"), 1s) AS calls FROM \"stat_statements_calls\" WHERE $timeFilter AND \"dbname\" =~ /^$dbname/ GROUP BY dbname, time(5m) fill(none))",
     "rawSql": "select\n  time,\n  sum(avg) as qps\nfrom (\nselect\n  $__timeGroup(time, $__interval),\n  dbname,\n  avg((c - c_lag) / extract(epoch from time - time_lag))\nfrom (\n        select \n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag,\n          dbname\n        from stat_statements_calls\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1, 2\n) y\ngroup by 1\norder by 1\n"
    }
   ]
  },
  {
   "title": "Query runtime",
   "type": "singlestat",
   "description": "Avg. of all DBs over the whole selected period for regular (>10 calls) queries",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "avg_query_runtime_per_db",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(runtime) from (select non_negative_derivative(mean(\"total_time\")) / non_negative_derivative(mean(\"calls\")) as runtime from \"stat_statements\" WHERE \"dbname\" =~ /^$dbname/ AND $timeFilter AND calls > 100 GROUP BY dbname, time($__interval) fill(none))",
     "rawSql": "select\n  $__timeGroup(time, $__interval),\n  avg((tt-tt_lag)::numeric / (c-c_lag))\nfrom (\n        select \n          (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,\n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, dbname\n        from stat_statements_calls\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)\n) x\nwhere c > c_lag and tt >= tt_lag and c > 100\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Total DB size ch.",
   "type": "singlestat",
   "description": "Sum of all DB changes over the whole selected period",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "diff",
   "targets": [
    {
     "alias": "db_size_change_last_hour",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(diff) from (SELECT last(\"size_b\")  - first(\"size_b\") as diff FROM \"db_size\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY dbname, time(3650d) fill(none))",
     "rawSql": "select\n  time,\n  sum(last_db_size) as total_size\nfrom (\nselect\n  time,\n  dbname,\n  max(last_value) as last_db_size\nfrom (\n  select\n    date_trunc('hour', time) as time,\n    dbname,\n    last_value((data->'size_b')::int8) over w\n  from\n    db_size\n  where \n    dbname in ($dbname)\n    and $__timeFilter(time)\n  window w as (\n     partition by dbname, date_trunc('hour', time) order by time rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\n  )\n) x\ngroup by 1, 2\n) y\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Total table bloat ch. (approx.)",
   "type": "singlestat",
   "description": "Sum of all DBs. Based on a SQL based approximate.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "diff",
   "targets": [
    {
     "alias": "Bloat size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "table_bloat_approx_summary",
     "query": "select sum(bloat) from (SELECT last(\"approx_free_space_b\") - first(\"approx_free_space_b\") as bloat FROM \"table_bloat_approx_summary\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY dbname, time(3650d) fill(none))",
     "rawSql": "select\n  $__unixEpochFrom() as time,\n  sum(bloat) from\n(\n\n  select distinct on (dbname)\n    dbname,\n    time,\n    (data->'approx_table_bloat_b')::int8 as bloat\n  from\n    table_bloat_approx_summary_sql\n  where \n    dbname in ($dbname)\n    and $__timeFilter(time)\n  order by\n    dbname, time\n\n) a    \n\nunion all\n\nselect\n  $__unixEpochTo() as time,\n  sum(bloat)\nfrom (\n\n  select distinct on (dbname)\n    dbname,\n    time,\n    (data->'approx_table_bloat_b')::int8 as bloat\n  from\n    table_bloat_approx_summary_sql\n  where \n    dbname in ($dbname)\n    and $__timeFilter(time)\n  order by\n    dbname, time desc\n    \n) b",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load Avg.",
   "type": "singlestat",
   "description": "Avg. of all selected DB-s for the whole period",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  avg((data->'load_5min')::float8)\nFROM\n  cpu_load\nWHERE\n  $__timeFilter(time)\n  AND dbname in ($dbname)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "select non_negative_derivative(mean(\"xact_commit\")) + non_negative_derivative(mean(\"xact_rollback\")) from \"db_stats\" WHERE \"dbname\" =~ /^$dbname/ AND $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg(((c - c_lag) + (r - r_lag)) / extract(epoch from time - time_lag)) as \"TPS\"\nfrom (\n        select \n          (data->'xact_commit')::int8 as c, lag((data->'xact_commit')::int8) over w as c_lag,\n          (data->'xact_rollback')::int8 as r, lag((data->'xact_rollback')::int8) over w as r_lag,\n          time, lag(time) over w as time_lag, dbname\n        from db_stats\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)        \n) x\nwhere c >= c_lag and r >= r_lag and time > time_lag\ngroup by 1, 2\norder by 1\n"
    }
   ]
  },
  {
   "title": "Queries per Second",
   "type": "graph",
   "description": "Based on pg_stat_statements.calls",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((c - c_lag) / extract(epoch from time - time_lag)) as \"QPS\"\nfrom (\n        select \n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, lag(time) over w as time_lag, dbname\n        from stat_statements_calls\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)        \n) x\nwhere c >= c_lag and time > time_lag\ngroup by 1, 2\norder by 1\n"
    }
   ]
  },
  {
   "title": "Avg. query runtime",
   "type": "graph",
   "description": "Requires \"pg_stat_statements\" on server. For regular queries (calls >10)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_statements",
     "query": "select non_negative_derivative(last(\"total_time\")) / non_negative_derivative(last(\"calls\")) from \"stat_statements\" WHERE \"dbname\" =~ /^$dbname/ AND $timeFilter AND calls > 100 GROUP BY dbname, time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((tt-tt_lag)::numeric / (c-c_lag)) as avg_query_runtime\nfrom (\n        select \n          (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,\n          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,\n          time, dbname\n        from stat_statements_calls\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)\n) x\nwhere c > c_lag and tt >= tt_lag\ngroup by 1, 2\norder by 1"
    }
   ]
  },
  {
   "title": "TX error ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (non_negative_derivative(mean(\"xact_rollback\")) / (non_negative_derivative(mean(\"xact_commit\")) + non_negative_derivative(mean(\"xact_rollback\"))) * 100) FROM \"db_stats\" WHERE $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg(case when c = c_lag and r = r_lag then 0 else (((r - r_lag)::numeric * 100) / ((c - c_lag) + (r - r_lag)) ) end) as tx_err_ratio\nfrom (\n        select \n          (data->'xact_commit')::int8 as c, lag((data->'xact_commit')::int8) over w as c_lag,\n          (data->'xact_rollback')::int8 as r, lag((data->'xact_rollback')::int8) over w as r_lag,\n          time, dbname\n        from db_stats\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)        \n) x\nwhere c >= c_lag and r >= r_lag\ngroup by 1, 2\norder by 1, 2"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT last(\"size_b\")   FROM \"db_size\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval) as time,\n  dbname,\n  avg((data->'size_b')::int8) db_size\nfrom\n  db_size\nwhere \n  dbname in ($dbname)\n  and $__timeFilter(time)\ngroup by\n  1, 2\norder by\n  1, 2"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "description": "Requires according \"metric fetching helpers\" on the monitored server",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->'load_5min')::float8)\nFROM\n  cpu_load\nWHERE\n  $__timeFilter(time)\n  AND dbname in ($dbname)\nGROUP BY 1, 2\nORDER BY 1, 2\n"
    }
   ]
  },
  {
   "title": "Temp bytes written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  sum(tb-tb_lag) as temp_bytes\nfrom (\n        select \n          (data->>'temp_bytes')::int8 as tb, lag((data->>'temp_bytes')::int8) over w as tb_lag,\n          time, dbname\n        from db_stats\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)\n) x\nwhere tb >= tb_lag\ngroup by 1, 2\norder by 1, 2\n"
    }
   ]
  },
  {
   "title": "WAL rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wal",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((wal-wal_lag) / extract(epoch from (time - time_lag))) as \"WAL rate\"\nfrom (\n        select \n          (data->>'xlog_location_b')::int8 as wal, lag((data->>'xlog_location_b')::int8) over w as wal_lag,\n          time, lag(time) over w as time_lag, dbname\n        from wal\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)\n) x\nwhere wal >= wal_lag and time > time_lag\ngroup by 1, 2\norder by 1, 2",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared buffer hit ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "query": "SELECT ( non_negative_derivative(mean(\"blks_hit\")) / (non_negative_derivative(mean(\"blks_hit\")) + non_negative_derivative(mean(\"blks_read\")))) * 100 FROM \"db_stats\" WHERE \"dbname\" =~ /^$dbname$/ AND  $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "rawSql": "select\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg( case when hit=hit_lag and read=read_lag then null else (hit-hit_lag)::numeric / ((hit-hit_lag) + (read-read_lag))*100 end) as \"Shared buffers hit ratio\"\nfrom (\n        select \n          (data->>'blks_hit')::int8 as hit, lag((data->>'blks_hit')::int8) over w as hit_lag,\n          (data->>'blks_read')::int8 as read, lag((data->>'blks_read')::int8) over w as read_lag,\n          time, dbname\n        from db_stats\n        where dbname in ($dbname) and $__timeFilter(time)\n        window w as (partition by dbname order by time)\n) x\nwhere hit >= hit_lag or read >= read_lag\ngroup by 1, 2\norder by 1, 2"
    }
   ]
  },
  {
   "title": "Non-idle sessions",
   "type": "graph",
   "description": "Based on pg_stat_activity info",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "backends",
     "query": "SELECT mean(\"idleintransaction\") + mean(\"waiting\") + mean(\"active\")  FROM \"backends\" WHERE \"dbname\" =~ /^$dbname$/ AND $timeFilter GROUP BY dbname, time($__interval) fill(none)",
     "rawSql": "SELECT\n  $__timeGroup(time, $agg_interval),\n  dbname,\n  avg((data->'idleintransaction')::int + (data->'waiting')::int + (data->'active')::int) as sessions\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\n  and dbname in ($dbname)\nGROUP BY\n  1, 2\nORDER BY\n  1, 2\n",
     "tags": [
      { "key": "dbname", "operator": "=~", "value": "/^$dbname$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}