{
 "title": "Table details",
 "tags": [
  "pgwatch3",
  "postgres"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbname", "query": { "query": "label_values(dbname)" } },
   {
    "name": "table",
    "query": {
     "query": "label_values(pgwatch3_table_stats_seq_scan{dbname=~\"$dbname\"}, table_full_name) "
    }
   },
   {
    "name": "agg_interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "IUD ($agg_interval tot.)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(increase(pgwatch3_table_stats_n_tup_ins{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval]))",
     "legendFormat": "INS"
    },
    {
     "expr": "max(increase(pgwatch3_table_stats_n_tup_upd{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval]))",
     "legendFormat": "UPD"
    },
    {
     "expr": "max(increase(pgwatch3_table_stats_n_tup_del{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval]))",
     "legendFormat": "DEL"
    }
   ]
  },
  {
   "title": "Seq. scans ($agg_interval tot.)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(increase(pgwatch3_table_stats_seq_scan{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval]))",
     "legendFormat": "seq_scan"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(pgwatch3_table_stats_table_size_b{dbname='$dbname',table_full_name=\"$table\"})",
     "legendFormat": "table_size"
    },
    {
     "expr": "max(pgwatch3_table_stats_total_relation_size_b{dbname='$dbname',table_full_name=\"$table\"})",
     "legendFormat": "total_relation_size"
    }
   ]
  },
  {
   "title": "Shared Buffers hit % ($agg_interval avg.)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * max(increase(pgwatch3_table_io_stats_heap_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) / max((increase(pgwatch3_table_io_stats_heap_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) + max(increase(pgwatch3_table_io_stats_heap_blks_read{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])))",
     "legendFormat": "heap"
    },
    {
     "expr": "100 * max(increase(pgwatch3_table_io_stats_idx_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) / max((increase(pgwatch3_table_io_stats_idx_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) + max(increase(pgwatch3_table_io_stats_idx_blks_read{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])))",
     "legendFormat": "idx"
    },
    {
     "expr": "100 * max(increase(pgwatch3_table_io_stats_toast_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) / (max(increase(pgwatch3_table_io_stats_toast_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) + max(increase(pgwatch3_table_io_stats_toast_blks_read{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])))",
     "legendFormat": "toast"
    },
    {
     "expr": "100 * max(increase(pgwatch3_table_io_stats_tidx_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) / (max(increase(pgwatch3_table_io_stats_tidx_blks_hit{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])) + max(increase(pgwatch3_table_io_stats_tidx_blks_read{dbname='$dbname',table_full_name=\"$table\"}[$agg_interval])))",
     "legendFormat": "tidx"
    }
   ]
  },
  {
   "title": "Block bandwith ($agg_interval tot.)",
   "type": "graph",
   "description": "Amount of block data read from the table, including cache and TOAST",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "8192 * (max(increase(pgwatch3_table_io_stats_heap_blks_hit{dbname='$dbname',table_full_name=\"$table\"})) + max(increase(pgwatch3_table_io_stats_heap_blks_read{dbname='$dbname',table_full_name=\"$table\"})))",
     "legendFormat": "heap"
    },
    {
     "expr": "8192 * (max(increase(pgwatch3_table_io_stats_idx_blks_hit{dbname='$dbname',table_full_name=\"$table\"})) + max(increase(pgwatch3_table_io_stats_idx_blks_read{dbname='$dbname',table_full_name=\"$table\"})))",
     "legendFormat": "idx"
    },
    {
     "expr": "8192 * (max(increase(pgwatch3_table_io_stats_toast_blks_hit{dbname='$dbname',table_full_name=\"$table\"})) + max(increase(pgwatch3_table_io_stats_toast_blks_read{dbname='$dbname',table_full_name=\"$table\"})))",
     "legendFormat": "toast"
    },
    {
     "expr": "8192 * (max(increase(pgwatch3_table_io_stats_tidx_blks_hit{dbname='$dbname',table_full_name=\"$table\"})) + max(increase(pgwatch3_table_io_stats_tidx_blks_read{dbname='$dbname',table_full_name=\"$table\"})))",
     "legendFormat": "tidx"
    }
   ]
  },
  {
   "title": "Time since last VACUUM",
   "type": "stat",
   "description": "Including both manual VACUUM and AUTOVACUUM",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgwatch3_table_stats_seconds_since_last_vacuum{dbname='$dbname',table_full_name=\"$table\"}"
    }
   ]
  },
  {
   "title": "Time since last ANALYZE",
   "type": "stat",
   "description": "Including both manual ANALYZE and AUTOVACUUM",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgwatch3_table_stats_seconds_since_last_analyze{dbname='$dbname',table_full_name=\"$table\"}"
    }
   ]
  }
 ]
}