apiVersion: 1

datasources:
  - name: pgwatch metrics (prometheus)
    uid: pgwatch-prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    isDefault: false
    version: 1
    editable: true