services:
  pgbench:
    environment:
      PGHOST: postgres
      PGUSER: pgwatch
      PGDATABASE: pgwatch
    command: >
      sh -c "pgbench --initialize --scale=50 && 
        pgbench --progress=5 --client=10 --jobs=2 --transactions=10000 && 
        pgbench --initialize --init-steps=d"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - pgbench