services:
  grafana:
    # to use specific Grafana image, e.g. grafana/grafana:11.5.6, update the dashboards provisioning folder below
    image: grafana/grafana:12.1.0
    container_name: grafana
    user: "0:0"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/postgres/1-global-db-overview.json
      GF_INSTALL_PLUGINS: marcusolsson-treemap-panel
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      # GF_FEATURE_TOGGLES_ENABLE: dashboardNewLayouts
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "../grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/pgwatch_dashboards.yml"
      # Uncomment the datasource version you want to use
      - "../grafana/postgres_datasource.yml:/etc/grafana/provisioning/datasources/postgres_datasource.yml"
      - "../grafana/prometheus_datasource.yml:/etc/grafana/provisioning/datasources/prometheus_datasource.yml"
      # Uncomment the dashboard version you want to use and comment out the other one.
      - "../grafana/postgres/v12:/var/lib/grafana/dashboards/postgres"
      - "../grafana/prometheus/v12:/var/lib/grafana/dashboards/prometheus"
    depends_on:
      postgres:
        condition: service_healthy