FROM ubuntu:16.04

RUN apt-get -q update && apt-get -qy install python3-pip \
    && mkdir /pgwatch3

###
### add webpy source and configure installed components
###

ADD webpy /pgwatch3/webpy
ADD docker/launch-wrapper-webui.sh /pgwatch3

# Get Web UI requirements
RUN pip3 install -U "pip < 21.0" && pip3 install -r /pgwatch3/webpy/requirements_pg_metrics.txt \
    && chgrp -R 0 /pgwatch3 \
    && chmod -R g=u /pgwatch3 \
    && mkdir /pgwatch3/persistent-config \
    && chgrp -R 0 /pgwatch3/webpy /pgwatch3/persistent-config \
    && chmod -R g=u /pgwatch3/webpy /pgwatch3/persistent-config


# Admin UI for configuring servers to be monitored
EXPOSE 8080

VOLUME /pgwatch3/persistent-config

USER 10001

ENTRYPOINT ["/pgwatch3/launch-wrapper-webui.sh"]
