FROM golang:1.18

# For showing Git version via 'pgwatch3 --version'
ARG GIT_HASH
ARG GIT_TIME
ENV GIT_HASH=${GIT_HASH}
ENV GIT_TIME=${GIT_TIME}

ADD src /pgwatch3
RUN cd /pgwatch3 && bash build_gatherer.sh


FROM ubuntu:20.04

RUN apt-get -q update && apt-get -qy install wget git && apt autoremove -y && mkdir /pgwatch3

ADD pgwatch3/metrics /pgwatch3/metrics
ADD pgwatch3/config /pgwatch3/config

# Copy over the compiled gatherer
COPY --from=0 /pgwatch3/pgwatch3 /pgwatch3

RUN chgrp -R 0 /pgwatch3 \
    && chmod -R g=u /pgwatch3

# pgwatch3 internal status endpoint
EXPOSE 8081
# Prometheus metrics scraping port
EXPOSE 9187

USER 10001

ENTRYPOINT ["/pgwatch3/pgwatch3"]
