{
 "title": "Alert Template",
 "tags": [ "pgwatch3" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "1 active primary per cluster",
   "type": "graph",
   "description": "1 primary - no less, no more. PG 10+ (pg_control_system().system_identifier)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  time,\n  (select string_agg(distinct dbname, ',') from wal where tag_data->>'sys_id' = sys_id and $__timeFilter(time)) as cluster_members,\n  sum(is_primary) as primary_count\nFROM (\nSELECT\n  $__timeGroup(time, '1m'),\n  tag_data->>'sys_id' as sys_id,\n  max(case when data->>'in_recovery_int' = '0' then 1 else 0 end) as is_primary\nFROM\n  wal\nWHERE\n  $__timeFilter(time)\n  AND tag_data ? 'sys_id'\nGROUP BY 1, 2\n) x\nGROUP BY time, sys_id\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Instance connections used %",
   "type": "graph",
   "description": "100.0 * connections / max_connections",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n time,\n dbname,\n /* NB! the selected $__timeFilter should be greater than the 'settings' metric's interval, i.e. 2h+ when using some default preset config */\n 100.0 * max_total_sessions / (select coalesce((data->'max_connections')::int, 1) from settings where dbname = x.dbname and $__timeFilter(time) order by time desc limit 1) as pct_used\nFROM (\nSELECT\n  $__timeGroup(time, $__interval),\n  dbname,\n  max((data->'instance_total')::int) as max_total_sessions\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\nGROUP BY 1, 2\nORDER BY 1, 2\n) x\nORDER BY 1, 2\n"
    }
   ]
  },
  {
   "title": "Disk usage > 90 %",
   "type": "graph",
   "description": "Assumes psutil* helpers are installed",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT * FROM (\nSELECT\n  $__timeGroup(time, $__interval),\n  dbname,\n  avg((data->'percent')::float8) as percent_used\nFROM\n  psutil_disk\nWHERE\n  $__timeFilter(time)\n  AND tag_data->>'dir_or_tablespace' in ('data_directory', 'pg_wal', 'log_directory')\nGROUP BY 1, 2\n) x\n-- WHERE percent_used > 75 /* uncomment to not show \"healthy\" */\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Inactive replication slots",
   "type": "graph",
   "description": "WAL-s will be reserved until disk runs out...",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  dbname,\n  avg((data->'non_active_int')::int) as inactive_repl_slots\nFROM\n  replication_slots\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  1, 2\nORDER BY\n  1, 2\n"
    }
   ]
  },
  {
   "title": "Waiting sessions > 10",
   "type": "graph",
   "description": "Could be both lock or IO",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__timeGroup(time, $__interval),\n  dbname,\n  max((data->'waiting')::int) as waiting\nFROM\n  backends\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  1, 2\nORDER BY\n  1, 2"
    }
   ]
  }
 ]
}