{{- if .Values.grafana.noAnonymous -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgwatch3.fullname" . }}-grafana
  labels:
{{ include "pgwatch3.labels" . | indent 4 }}
type: Opaque
data:
  user: {{ .Values.grafana.user | b64enc | quote }}
  {{- if .Values.grafana.password }}
  password: {{ .Values.grafana.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}