{
 "title": "Sessions overview",
 "tags": [
  "pgwatch",
  "postgres",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbname", "query": { "query": "label_values(dbname)" } },
   { "name": "agg_interval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "TPS / QPS ($agg_interval avg.)",
   "type": "timeseries",
   "description": "QPS is an approximation. Requires pg_stat_statements to be installed",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(pgwatch_db_stats_xact_commit{dbname='$dbname'}[$agg_interval])) + avg(rate(pgwatch_db_stats_xact_rollback{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "TPS"
    },
    {
     "expr": "avg(rate(pgwatch_stat_statements_calls_calls{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Session activity ($agg_interval max., log base 2)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch_backends_total{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(max_over_time(pgwatch_backends_active{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Active"
    },
    {
     "expr": "max(pgwatch_backends_max_connections{dbname='$dbname'})",
     "legendFormat": "max_connections"
    },
    {
     "expr": "max(max_over_time(pgwatch_backends_waiting{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Waiting"
    },
    {
     "expr": "max(max_over_time(pgwatch_backends_idleintransaction{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Idle in TX"
    },
    {
     "expr": "max(increase(pgwatch_db_stats_deadlocks{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "Longest query duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch_backends_longest_query_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Longest query "
    },
    {
     "expr": "max(avg_over_time(pgwatch_backends_avg_query_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Avg. query"
    }
   ]
  },
  {
   "title": "Longest TX duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch_backends_longest_tx_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Longest TX"
    },
    {
     "expr": "max(avg_over_time(pgwatch_backends_avg_tx_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Avg. TX"
    }
   ]
  },
  {
   "title": "Longest session duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch_backends_longest_session_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Longest session"
    },
    {
     "expr": "max(avg_over_time(pgwatch_backends_avg_session_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Avg. session"
    }
   ]
  },
  {
   "title": "Longest wait duration",
   "type": "timeseries",
   "description": "\"No data\" means no waiting detected",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max(max_over_time(pgwatch_backends_longest_waiting_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Longest wait duration"
    },
    {
     "expr": "max(avg_over_time(pgwatch_backends_avg_waiting_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Avg. wait duration"
    }
   ]
  },
  {
   "title": "Autovacuum max. duration / # workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "max(avg_over_time(pgwatch_backends_longest_autovacuum_seconds{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "AV duration"
    },
    {
     "expr": "max(max_over_time(pgwatch_backends_av_workers{dbname='$dbname'}[$agg_interval]))",
     "legendFormat": "Active AV workers"
    }
   ]
  }
 ]
}