{
 "title": "Stored Procedures (Prometheus)",
 "description": "Stored procedures and functions monitoring using Prometheus data source",
 "tags": [
  "pgwatch",
  "prometheus",
  "functions",
  "procedures",
  "performance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "Database",
    "query": "label_values(pgwatch_instance_up, dbname)"
   },
   { "name": "agg_interval", "label": "Aggregation interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Stored Procedures Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Function Count by Database",
   "type": "stat",
   "description": "Total number of functions/procedures by database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (dbname) (pgwatch_sproc_details_calls{dbname=~\"$dbname\"})",
     "legendFormat": "{{dbname}} - Functions"
    }
   ]
  },
  {
   "title": "Functions by Language",
   "type": "piechart",
   "description": "Functions by language",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (language) (pgwatch_sproc_details_calls{dbname=~\"$dbname\"})",
     "legendFormat": "{{language}}"
    }
   ]
  },
  { "title": "Function Call Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Function Calls Per Second",
   "type": "timeseries",
   "description": "Function calls per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (dbname) (rate(pgwatch_sproc_details_calls{dbname=~\"$dbname\"}[$agg_interval]))",
     "legendFormat": "{{dbname}} - Calls/sec"
    }
   ]
  },
  {
   "title": "Function Execution Time Per Second",
   "type": "timeseries",
   "description": "Function execution time per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (dbname) (rate(pgwatch_sproc_details_total_time{dbname=~\"$dbname\"}[$agg_interval]))",
     "legendFormat": "{{dbname}} - Time/sec"
    }
   ]
  },
  { "title": "Top Functions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top 20 Functions by Call Rate",
   "type": "table",
   "description": "Most called functions",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(20, sum by (sproc_name, schema_name, dbname, language) (rate(pgwatch_sproc_details_calls{dbname=~\"$dbname\"}[$agg_interval])))",
     "legendFormat": "Calls/sec"
    },
    {
     "expr": "pgwatch_sproc_details_calls{dbname=~\"$dbname\"}",
     "legendFormat": "Total Calls"
    },
    {
     "expr": "pgwatch_sproc_details_total_time{dbname=~\"$dbname\"} / pgwatch_sproc_details_calls{}",
     "legendFormat": "Avg Time (ms)"
    },
    {
     "expr": "pgwatch_sproc_details_total_time{dbname=~\"$dbname\"}",
     "legendFormat": "Total Time (ms)"
    }
   ]
  },
  {
   "title": "Top 20 Functions by Time Consumption",
   "type": "table",
   "description": "Functions consuming the most time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(20, sum by (sproc_name, schema_name, dbname, language) (rate(pgwatch_sproc_details_total_time{dbname=~\"$dbname\"}[$agg_interval])))",
     "legendFormat": "Time/sec (ms)"
    },
    {
     "expr": "rate(pgwatch_sproc_details_calls{dbname=~\"$dbname\"}[$agg_interval])",
     "legendFormat": "Calls/sec"
    },
    {
     "expr": "pgwatch_sproc_details_total_time{dbname=~\"$dbname\"} / pgwatch_sproc_details_calls{}",
     "legendFormat": "Avg Time (ms)"
    },
    {
     "expr": "pgwatch_sproc_details_self_time{dbname=~\"$dbname\"}",
     "legendFormat": "Self Time (ms)"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Function Performance Summary",
   "type": "stat",
   "description": "Current function performance summary",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgwatch_sproc_details_calls{dbname=~\"$dbname\"}[$agg_interval]))",
     "legendFormat": "Total Calls/sec"
    },
    {
     "expr": "sum(rate(pgwatch_sproc_details_total_time{dbname=~\"$dbname\"}[$agg_interval]))",
     "legendFormat": "Total Time/sec"
    },
    {
     "expr": "avg(pgwatch_sproc_details_total_time{dbname=~\"$dbname\"} / pgwatch_sproc_details_calls{})",
     "legendFormat": "Avg Function Time"
    },
    {
     "expr": "count(count by (sproc_name) (pgwatch_sproc_details_calls{dbname=~\"$dbname\"}))",
     "legendFormat": "Total Functions"
    }
   ]
  }
 ]
}