# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import pgwatch_pb2 as pgwatch__pb2


class ReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMeasurements = channel.unary_unary(
                '/Receiver/UpdateMeasurements',
                request_serializer=pgwatch__pb2.MeasurementEnvelope.SerializeToString,
                response_deserializer=pgwatch__pb2.Reply.FromString,
                )
        self.SyncMetric = channel.unary_unary(
                '/Receiver/SyncMetric',
                request_serializer=pgwatch__pb2.SyncReq.SerializeToString,
                response_deserializer=pgwatch__pb2.Reply.FromString,
                )
        self.DefineMetrics = channel.unary_unary(
                '/Receiver/DefineMetrics',
                request_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
                response_deserializer=pgwatch__pb2.Reply.FromString,
                )


class ReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateMeasurements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefineMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMeasurements': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMeasurements,
                    request_deserializer=pgwatch__pb2.MeasurementEnvelope.FromString,
                    response_serializer=pgwatch__pb2.Reply.SerializeToString,
            ),
            'SyncMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMetric,
                    request_deserializer=pgwatch__pb2.SyncReq.FromString,
                    response_serializer=pgwatch__pb2.Reply.SerializeToString,
            ),
            'DefineMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.DefineMetrics,
                    request_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                    response_serializer=pgwatch__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Receiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Receiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateMeasurements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Receiver/UpdateMeasurements',
            pgwatch__pb2.MeasurementEnvelope.SerializeToString,
            pgwatch__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Receiver/SyncMetric',
            pgwatch__pb2.SyncReq.SerializeToString,
            pgwatch__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DefineMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Receiver/DefineMetrics',
            google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            pgwatch__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
