add-real-dbname: false
add-system-identifier: false
aes-gcm-keyphrase: ""
aes-gcm-keyphrase-file: ""
aes-gcm-password-to-encrypt: ""
batching-delay-ms: 250
config: ""
connection:
    dbname: pgwatch3
    host: localhost
    init: false
    password: ""
    pg-require-ssl: false
    port: "5432"
    servers-refresh-loop-seconds: 120
    user: pgwatch3
direct-os-stats: false
emergency-pause-triggerfile: /tmp/pgwatch3-emergency-pause
instance-level-cache-max-seconds: 30
logging:
    log-file: ""
    log-file-age: 0
    log-file-format: json
    log-file-number: 0
    log-file-rotate: false
    log-file-size: 100
    log-level: info
max-parallel-connections-per-db: 2
metric:
    datastore: postgres
    group: ""
    json-storage-file: ""
    metrics-folder: ""
    no-helper-functions: false
    pg-metric-store-conn-str: postgresql://foo:baz@bar/test
    pg-retention-days: 14
    prometheus-async-mode: false
    prometheus-listen-addr: 0.0.0.0
    prometheus-namespace: pgwatch3
    prometheus-port: 9187
min-db-size-mb: 0
ping: false
real-dbname-field: real_dbname
system-identifier-field: sys_id
try-create-listed-exts-if-missing: ""
use-conn-pooling: false
version: false
webui:
    web-addr: :8080
    web-password: ""
    web-user: ""
