{
 "title": "Global Health",
 "tags": [ "pgwatch3" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "top_limit", "query": "1,3,5,10" }
  ]
 },
 "panels": [
  {
   "title": "Monitored primary DB-s ",
   "type": "gauge",
   "description": "Please adjust the markers as needed! NB! Also the default query assumes that all DBs are separate instances. If not so change the query to add some filters or groupings based on the wal.sys_id column for example or the configured_dbs.continuous_discovery_prefix if using the DB auto-discovery modes. The same applies also for the below \"top\" table panels.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(distinct dbname)\nFROM wal\nWHERE\n  $__timeFilter(\"time\")\n  AND (data->'in_recovery_int')::int = 0"
    }
   ]
  },
  {
   "title": "Monitored replica DB-s",
   "type": "gauge",
   "description": "Please adjust the markers as needed! NB! Also the default query assumes that all DBs are separate instances. If not so change the query to add some filters or groupings based on the wal.sys_id column for example or the configured_dbs.continuous_discovery_prefix if using the DB auto-discovery modes. The same applies also for the below \"top\" table panels.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  0 AS \"time\",\n  count(distinct dbname)\nFROM\n  wal\nWHERE\n  $__timeFilter(\"time\")\n  AND (data->'in_recovery_int')::int = 1"
    }
   ]
  },
  {
   "title": "Offline nodes",
   "type": "table",
   "description": "Configured to be monitored but no recent data",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n dbname,\n (SELECT case when data->>'in_recovery_int' = '0' then 'primary' else 'replica' end from wal where time > now() - '15min'::interval and dbname = c.dbname order by time desc limit 1) as last_role,\n (SELECT (extract(epoch from now() - time))::int from db_stats where dbname = c.dbname order by time desc limit 1) as last_seen,\n (SELECT (data->'postmaster_uptime_s')::int from db_stats where dbname = c.dbname order by time desc limit 1) as last_seen_uptime\nFROM\n  (select dbname, max(time) from configured_dbs where time between now() - '15min'::interval and now() group by dbname) c /* 10min ping interval hardcoded in collector */\nWHERE\n  NOT EXISTS (\n select dbname from db_stats where $__timeFilter(\"time\") and dbname = c.dbname union \n select dbname from pgbouncer_stats where $__timeFilter(\"time\") and dbname = c.dbname \n)"
    }
   ]
  },
  {
   "title": "Top $top_limit by TX rollback %",
   "type": "table",
   "description": "Last $__interval average. 2 /5 % threshold  defaults.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select * from (\nselect\n  dbname,\n  avg((roll-roll_lag)::numeric / ((roll-roll_lag) + (comm-comm_lag)))*100 as \"rollback_ratio\"\nfrom (\n  select\n      dbname,\n      time,\n      (data->>'xact_rollback')::int8 as roll, lag((data->>'xact_rollback')::int8) over w as roll_lag,\n      (data->>'xact_commit')::int8 as comm, lag((data->>'xact_commit')::int8) over w as comm_lag\n  FROM\n      db_stats\n  WHERE\n    $__timeFilter(\"time\")\n    window w as (partition by dbname order by time)\n) x\nWHERE comm > comm_lag or roll > roll_lag\nGROUP BY 1\n) y\nWHERE rollback_ratio > 0\nORDER BY 2 DESC\nLIMIT $top_limit\n"
    }
   ]
  },
  {
   "title": "Top $top_limit by longest TX time",
   "type": "table",
   "description": "Includes \"idle in transaction\" TX.  5 / 10 min default thresholds",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\nSELECT\n  dbname,\n  max((data->'longest_tx_seconds')::int) AS longest_tx_seconds\nFROM\n  backends\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY\n  dbname\n) x\nWHERE longest_tx_seconds > 0\nORDER BY 2 DESC\nLIMIT $top_limit"
    }
   ]
  },
  {
   "title": "Top $top_limit by blocked sessions",
   "type": "table",
   "description": "Assumes get_stat_activity() helper for non-privileged monitoring users",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n dbname,\n max((data->'waiting')::int) AS \"waiting\"\nFROM\n  backends\nWHERE\n  $__timeFilter(\"time\")\n  AND (data->'waiting')::int > 0\nGROUP BY\n  1\nORDER BY\n  2 DESC NULLS LAST\nLIMIT\n  $top_limit"
    }
   ]
  },
  {
   "title": "Top $top_limit by used connections",
   "type": "table",
   "description": "Assumes get_stat_activity() helper for non-privileged monitoring users",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n dbname,\n round(100 * instance_total::numeric / max_connections, 1) AS \"pct_used\",\n instance_total AS used_connections,\n max_connections\nFROM\n  (\n    select\n      distinct on (dbname)\n      dbname,\n      (data->'max_connections')::int as max_connections,\n      (data->'instance_total')::int as instance_total\n    FROM\n      backends\n    WHERE\n      $__timeFilter(time)\n    order by dbname, time desc\n  ) x\nORDER BY\n  2 DESC NULLS LAST\nLIMIT\n  $top_limit"
    }
   ]
  },
  {
   "title": "Top $top_limit by temp. files",
   "type": "table",
   "description": "100 MB / 1 GB default threshold",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from (\nselect\n  dbname,\n  avg((tb-tb_lag) / (etime - lag_etime))*60 as \"temp_bytes_per_minute\"\nfrom (\n        select\n          dbname,\n          (data->>'temp_bytes')::int8 as tb, lag((data->>'temp_bytes')::int8) over w as tb_lag,\n          (extract(epoch from time))::int8 as etime,\n          (lag(extract(epoch from time)) over w)::int8 as lag_etime\n        from db_stats\n        where $__timeFilter(time)\n        window w as (partition by dbname order by time)\n) x\nwhere\n  tb >= tb_lag and etime > lag_etime\ngroup by\n  dbname\n) y\nwhere temp_bytes_per_minute > 0\norder by 2 desc\nlimit $top_limit"
    }
   ]
  },
  {
   "title": "Top $top_limit by replication lag",
   "type": "table",
   "description": "1 / 16 MB default thresholds",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "select * from (\nselect \n  dbname,\n  max((data->'replay_lag_b')::int8) as replay_lag_b\nfrom\n  replication\nwhere\n  (data->'replay_lag_b')::int8 > 0\ngroup by\n  dbname\n) x\norder by 2 desc\nlimit $top_limit"
    }
   ]
  },
  {
   "title": "Lowest $top_limit by free disk %",
   "type": "table",
   "description": "Assumes \"psutil_disk\" helper. 10 / 5% default warning thresholds",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select * from (\nselect \n  dbname,\n  max((data->'percent')::float) as used_percent\nfrom\n  psutil_disk\nwhere\n  $__timeFilter(\"time\")\n  and (data->'percent')::float > 0\ngroup by\n  dbname\n) x\norder by 2 desc nulls last\nlimit $top_limit"
    }
   ]
  },
  {
   "title": "Top $top_limit by CPU utilization %",
   "type": "table",
   "description": "Assumes \"psutil_cpu\" helpers are installed and configured",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n dbname,\n round(max((data->'cpu_utilization')::numeric), 1) AS \"cpu_utilization\"\nFROM\n  psutil_cpu\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY\n  1\nORDER BY\n  2 DESC NULLS LAST\nLIMIT\n  $top_limit"
    }
   ]
  },
  {
   "title": "Top $top_limit by WAL folder size",
   "type": "table",
   "description": "Needs \"get_wal_size\" helper for unprivileged monitoring users",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n dbname,\n max((data->'wal_size_b')::int8) as wal_size\nFROM\n  wal_size\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY\n  1\nORDER BY\n  2 DESC NULLS LAST\nLIMIT\n  $top_limit"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "content": "Brought to you by: <a href=\"https://www.cybertec-postgresql.com/en/\"><img src=\"https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png\" alt=\"Cybertec – The PostgreSQL Database Company\"></a>"
  }
 ]
}