# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pgwatch.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpgwatch.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x17\n\x05Reply\x12\x0e\n\x06logmsg\x18\x01 \x01(\t\"\xcd\x01\n\x13MeasurementEnvelope\x12\x0e\n\x06\x44\x42Name\x18\x01 \x01(\t\x12\x12\n\nMetricName\x18\x02 \x01(\t\x12\x38\n\nCustomTags\x18\x03 \x03(\x0b\x32$.MeasurementEnvelope.CustomTagsEntry\x12%\n\x04\x44\x61ta\x18\x04 \x03(\x0b\x32\x17.google.protobuf.Struct\x1a\x31\n\x0f\x43ustomTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"I\n\x07SyncReq\x12\x0e\n\x06\x44\x42Name\x18\x01 \x01(\t\x12\x12\n\nMetricName\x18\x02 \x01(\t\x12\x1a\n\tOperation\x18\x03 \x01(\x0e\x32\x07.SyncOp*>\n\x06SyncOp\x12\r\n\tInvalidOp\x10\x00\x12\t\n\x05\x41\x64\x64Op\x10\x01\x12\x0c\n\x08\x44\x65leteOp\x10\x02\x12\x0c\n\x08\x44\x65\x66ineOp\x10\x03\x32\x90\x01\n\x08Receiver\x12\x32\n\x12UpdateMeasurements\x12\x14.MeasurementEnvelope\x1a\x06.Reply\x12\x1e\n\nSyncMetric\x12\x08.SyncReq\x1a\x06.Reply\x12\x30\n\rDefineMetrics\x12\x17.google.protobuf.Struct\x1a\x06.ReplyB\x06Z\x04.;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pgwatch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004.;pb'
  _globals['_MEASUREMENTENVELOPE_CUSTOMTAGSENTRY']._options = None
  _globals['_MEASUREMENTENVELOPE_CUSTOMTAGSENTRY']._serialized_options = b'8\001'
  _globals['_SYNCOP']._serialized_start=355
  _globals['_SYNCOP']._serialized_end=417
  _globals['_REPLY']._serialized_start=47
  _globals['_REPLY']._serialized_end=70
  _globals['_MEASUREMENTENVELOPE']._serialized_start=73
  _globals['_MEASUREMENTENVELOPE']._serialized_end=278
  _globals['_MEASUREMENTENVELOPE_CUSTOMTAGSENTRY']._serialized_start=229
  _globals['_MEASUREMENTENVELOPE_CUSTOMTAGSENTRY']._serialized_end=278
  _globals['_SYNCREQ']._serialized_start=280
  _globals['_SYNCREQ']._serialized_end=353
  _globals['_RECEIVER']._serialized_start=420
  _globals['_RECEIVER']._serialized_end=564
# @@protoc_insertion_point(module_scope)
