pgwatch3:
  service:
    type: NodePort
    servicePort: 8081
    nodePort: 30000
  noAnonymous: false
  testDBEnabled: true

web:
  service:
    type: NodePort
    servicePort: 8080
    nodePort: 30001
  noAnonymous: false
  user: pgwatch3
  password: password

grafana:
  service:
    type: NodePort
    servicePort: 3000
    nodePort: 30002
  noAnonymous: false
  user: pgwatch3
  password: password

exporter:
  service:
    type: NodePort
    servicePort: 9187
    nodePort: 30003
  ingress:
    enabled: true
