---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pgwatch3-deployment
    labels:
      app: pgwatch3
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: pgwatch3
    template:
      metadata:
        labels:
          app: pgwatch3
      spec:
        containers:
          - name: pgwatch3
            image: cybertec/pgwatch3-postgres:latest
            ports:
              - containerPort: 8080
              - containerPort: 8081
              - containerPort: 5432
              - containerPort: 3000
            volumeMounts:
              - mountPath: /pgwatch3/persistent-config
                name: pgwatch3-config
              - mountPath: /var/lib/postgresql
                name: pgwatch3-postgresql
              - mountPath: /var/lib/grafana
                name: pgwatch3-grafana
            livenessProbe:
              exec:
                command:
                  - /usr/bin/pg_isready
                  - -qU
                  - pgwatch3
              initialDelaySeconds: 30
              periodSeconds: 30
        volumes:
          - name: pgwatch3-config
            persistentVolumeClaim:
              claimName: pgwatch3-config
          - name: pgwatch3-postgresql
            persistentVolumeClaim:
              claimName: pgwatch3-postgresql
          - name: pgwatch3-grafana
            persistentVolumeClaim:
              claimName: pgwatch3-grafana
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pgwatch3-config
    labels:
      app: pgwatch3
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pgwatch3-postgresql
    labels:
      app: pgwatch3
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pgwatch3-grafana
    labels:
      app: pgwatch3
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
#---
#  kind: Service
#  apiVersion: v1
#  metadata:
#    name: pgwatch3-webui
#  spec:
#    type: NodePort
#    selector:
#      app: pgwatch3
#    ports:
#      - port: 8080
#        protocol: TCP
#        targetPort: 8080
#---
#  kind: Service
#  apiVersion: v1
#  metadata:
#    name: pgwatch3-grafana
#  spec:
#    type: NodePort
#    selector:
#      app: pgwatch3
#    ports:
#      - port: 3000
#        protocol: TCP
#        targetPort: 3000
