# This is simplistic sample and needs redeploy to change pgwatch3 metrics gathering settings for example.
# For bigger shops it's recommended to still go the Config DB route - i.e. one place to control all pgwatch3 gatherers.
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
        - name: pgwatch3
          image: cybertec/pgwatch3-daemon
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9187
            - containerPort: 8081
          env:
          - name: PW2_ADHOC_CONN_STR
            value: "host=localhost port=5432 user=postgres dbname=postgres"
          - name: PW2_ADHOC_NAME
            value: mypg1
          - name: PW2_DATASTORE
            value: prometheus
          - name: PW2_ADHOC_CONFIG
            value: prometheus
          - name: PW2_VERBOSE
            value: info
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
