// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pgwatch.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Receiver_UpdateMeasurements_FullMethodName = "/Receiver/UpdateMeasurements"
	Receiver_SyncMetric_FullMethodName         = "/Receiver/SyncMetric"
)

// ReceiverClient is the client API for Receiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceiverClient interface {
	UpdateMeasurements(ctx context.Context, in *MeasurementEnvelope, opts ...grpc.CallOption) (*Reply, error)
	SyncMetric(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*Reply, error)
}

type receiverClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiverClient(cc grpc.ClientConnInterface) ReceiverClient {
	return &receiverClient{cc}
}

func (c *receiverClient) UpdateMeasurements(ctx context.Context, in *MeasurementEnvelope, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Receiver_UpdateMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiverClient) SyncMetric(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Receiver_SyncMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiverServer is the server API for Receiver service.
// All implementations must embed UnimplementedReceiverServer
// for forward compatibility.
type ReceiverServer interface {
	UpdateMeasurements(context.Context, *MeasurementEnvelope) (*Reply, error)
	SyncMetric(context.Context, *SyncReq) (*Reply, error)
	mustEmbedUnimplementedReceiverServer()
}

// UnimplementedReceiverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReceiverServer struct{}

func (UnimplementedReceiverServer) UpdateMeasurements(context.Context, *MeasurementEnvelope) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMeasurements not implemented")
}
func (UnimplementedReceiverServer) SyncMetric(context.Context, *SyncReq) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMetric not implemented")
}
func (UnimplementedReceiverServer) mustEmbedUnimplementedReceiverServer() {}
func (UnimplementedReceiverServer) testEmbeddedByValue()                  {}

// UnsafeReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceiverServer will
// result in compilation errors.
type UnsafeReceiverServer interface {
	mustEmbedUnimplementedReceiverServer()
}

func RegisterReceiverServer(s grpc.ServiceRegistrar, srv ReceiverServer) {
	// If the following call pancis, it indicates UnimplementedReceiverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Receiver_ServiceDesc, srv)
}

func _Receiver_UpdateMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasurementEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverServer).UpdateMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Receiver_UpdateMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverServer).UpdateMeasurements(ctx, req.(*MeasurementEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _Receiver_SyncMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverServer).SyncMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Receiver_SyncMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverServer).SyncMetric(ctx, req.(*SyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Receiver_ServiceDesc is the grpc.ServiceDesc for Receiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Receiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Receiver",
	HandlerType: (*ReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMeasurements",
			Handler:    _Receiver_UpdateMeasurements_Handler,
		},
		{
			MethodName: "SyncMetric",
			Handler:    _Receiver_SyncMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pgwatch.proto",
}
