name: 'Setup Protobuf'
description: 'Install protoc and Go plugins with caching'
runs:
  using: 'composite'
  steps:
    - name: Cache protobuf tools
      uses: actions/cache@v4
      with:
        path: |
          ~/go/bin/protoc-gen-go
          ~/go/bin/protoc-gen-go-grpc
        key: ${{ runner.os }}-protoc-tools-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-protoc-tools-
    
    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: '25.x'
        repo-token: ${{ github.token }}
    
    - name: Install protobuf tools
      shell: bash
      run: |
        if [ ! -f ~/go/bin/protoc-gen-go ] || [ ! -f ~/go/bin/protoc-gen-go-grpc ]; then
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        fi
